import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'gu' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // ─── Navigation ───────────────────────────────────────────────
    'nav.about': 'About',
    'nav.science': 'Science',
    'nav.benefits': 'Benefits',
    'nav.nutrition': 'Nutrition',
    'nav.process': 'Process',
    'nav.comparison': 'Compare',
    'nav.recipes': 'Recipes',
    'nav.faq': 'FAQ',
    'nav.home': 'Home',
    'nav.blackGarlic': 'Black Garlic',
    'nav.peeledGarlic': 'Peeled Garlic',
    'nav.freezeDried': 'Freeze Dried',
    'nav.vacuumFried': 'Vacuum Fried',
    'nav.roastedMasala': 'Roasted Masala',
    'nav.b2b': 'B2B',
    'nav.contact': 'Contact',
    'nav.subtitle': 'Garlic Products Manufacturer',

    // ─── Hero (Home) ───────────────────────────────────────────────
    'home.hero.title': 'From Farm to Finished Food Products',
    'home.hero.description': 'Shubham Foods is a value-added garlic processing unit delivering consistent, quality-controlled products for both bulk and retail markets.',
    'home.hero.cta.products': 'Explore Products',
    'home.hero.cta.enquiry': 'Bulk Enquiry',

    // ─── Intro Section ─────────────────────────────────────────────
    'intro.badge': 'Gujarat, India',
    'intro.heading1': 'One facility.',
    'intro.heading2': 'Five product',
    'intro.heading3': 'lines. Consistent output.',
    'intro.p1': 'Shubham Foods operates a vertically integrated garlic processing facility — from locally sourced raw bulbs through a ten-stage processing pipeline to finished products across five distinct categories.',
    'intro.p2': 'Every product line shares the same upstream quality controls — colour sorting, centrifugal drying, and manual inspection — before branching into its own finishing process. The result is consistent, traceable output at scale.',
    'intro.stat1.value': '10+',
    'intro.stat1.label': 'Process Stages',
    'intro.stat2.value': '5',
    'intro.stat2.label': 'Product Lines',
    'intro.stat3.value': 'B2B',
    'intro.stat3.label': 'Bulk Ready',
    'intro.products.label': 'Product Lines',
    'intro.line1.label': 'Black Garlic',
    'intro.line1.sub': 'Fermented • Premium',
    'intro.line2.label': 'Peeled Frozen Garlic',
    'intro.line2.sub': 'Ingredient • Bulk',
    'intro.line3.label': 'Freeze Dried',
    'intro.line3.sub': 'Garlic & Banana',
    'intro.line4.label': 'Vacuum Fried',
    'intro.line4.sub': '7 Varieties',
    'intro.line5.label': 'Roasted Masala',
    'intro.line5.sub': 'Snack • Retail',

    // ─── Company About ─────────────────────────────────────────────
    'about.company.badge': 'About Shubham Foods',
    'about.company.title': 'Processing-Centered Food Manufacturing',
    'about.company.subtitle': 'We operate as a value-add processing company with a practical focus on input quality, process control, and reliable output across product categories.',
    'about.company.point1.title': 'Local Sourcing Network',
    'about.company.point1.desc': 'We source garlic from regional growers and plan procurement around variety, maturity, and processing suitability.',
    'about.company.point2.title': 'Mechanized + Manual Processing',
    'about.company.point2.desc': 'Our line combines equipment-led consistency with manual checks at key points for sorting and quality verification.',
    'about.company.point3.title': 'Expansion-Ready Infrastructure',
    'about.company.point3.desc': 'The facility is set up to scale batches and support multi-product operations without compromising process discipline.',
    'about.company.point4.title': 'Multiple Product Formats',
    'about.company.point4.desc': 'From raw and peeled to fermented and fried formats, we process garlic into products for culinary, retail, and industrial use.',

    // ─── Process Section ───────────────────────────────────────────
    'process.company.badge': 'Company Workflow',
    'process.company.title': 'Processing Flow Across Product Lines',
    'process.company.subtitle': 'Shared process stages are managed as a structured system before final packing or line-specific value addition.',
    'process.step1.title': 'Local Sourcing',
    'process.step1.desc': 'Garlic is procured from local supply clusters based on quality and seasonality.',
    'process.step2.title': 'Sun Drying',
    'process.step2.desc': 'Initial moisture balancing is carried out through controlled sun drying.',
    'process.step3.title': 'Tray Drying',
    'process.step3.desc': 'Product is moved to tray dryers for uniform controlled dehydration.',
    'process.step4.title': 'Bulb Breaker',
    'process.step4.desc': 'Bulbs are mechanically separated for downstream processing.',
    'process.step5.title': 'Peeling',
    'process.step5.desc': 'Peeling is performed through equipment and manual line checks.',
    'process.step6.title': 'Washing',
    'process.step6.desc': 'Cloves are washed to remove surface impurities and loose residues.',
    'process.step7.title': 'Centrifugal Drying',
    'process.step7.desc': 'Washed material is dried to target surface moisture levels.',
    'process.step8.title': 'Colour Sorting',
    'process.step8.desc': 'Optical and visual sorting is done for appearance consistency.',
    'process.step9.title': 'Manual Sorting',
    'process.step9.desc': 'Final hand sorting removes defects and non-conforming pieces.',
    'process.step10.title': 'Packaging or Further Processing',
    'process.step10.desc': 'Lots are packed or moved to fermentation, roasting, freeze drying, or vacuum frying lines.',

    // ─── Products Overview ─────────────────────────────────────────
    'products.badge': 'Products Overview',
    'products.title': 'Product Lines by Shubham Foods',
    'products.subtitle': 'Five processing lines built on a shared quality-controlled pipeline. From ingredient supply to finished snack formats.',
    'products.viewDetails': 'View Details',

    // ─── Product Details (Home) ────────────────────────────────────
    'productDetails.peeled.name': 'Peeled Garlic',
    'productDetails.peeled.p1': 'Processed through bulb breaker, peeling, washing, and controlled centrifugal drying.',
    'productDetails.peeled.p2': 'Suitable for horeca kitchens, processors, and repackers requiring clean garlic inputs.',
    'productDetails.peeled.p3': 'Supplied in chilled or ambient-compatible packs as per handling protocol.',
    'productDetails.freeze.name': 'Freeze Dried Products',
    'productDetails.freeze.p1': 'Low-temperature moisture removal for concentrated flavor and improved shelf life.',
    'productDetails.freeze.p2': 'Available as granules, powders, and flakes for seasoning and dry blend applications.',
    'productDetails.freeze.p3': 'Batch-level checks for moisture and particle consistency.',
    'productDetails.vacuum.name': 'Vacuum Fried Products',
    'productDetails.vacuum.p1': 'Vacuum frying supports crisp texture at lower thermal stress than conventional frying.',
    'productDetails.vacuum.p2': 'Can be supplied plain or seasoned for snack and ingredient use.',
    'productDetails.vacuum.p3': 'Oil quality and post-fry handling are controlled for consistent output.',
    'productDetails.roasted.name': 'Roasted Masala Garlic',
    'productDetails.roasted.p1': 'Roasted garlic integrated with controlled spice blending and coating.',
    'productDetails.roasted.p2': 'Developed for ready-to-eat snacking and flavor-forward retail products.',
    'productDetails.roasted.p3': 'Custom spice intensity and pack sizes available for channel-specific needs.',

    // ─── Black Garlic Section ──────────────────────────────────────
    'blackGarlic.badge': 'A Product by Shubham Foods',
    'blackGarlic.title': 'Black Garlic',
    'blackGarlic.subtitle': 'Black Garlic is produced through controlled fermentation of whole bulbs, resulting in a sweet, mellow profile valued in culinary applications and further food processing.',
    'blackGarlic.card1.title': 'Controlled Fermentation',
    'blackGarlic.card1.desc': 'Temperature, humidity, and duration are managed batch by batch to deliver consistent texture, color, and flavor progression.',
    'blackGarlic.card2.title': 'Culinary Value',
    'blackGarlic.card2.desc': 'The product offers umami depth, natural sweetness, and low pungency, making it useful in sauces, marinades, condiments, and premium ready-to-eat formats.',
    'blackGarlic.card3.title': 'Processing Utility',
    'blackGarlic.card3.desc': 'Black Garlic can be supplied for direct culinary use or as an input for blends, spreads, seasoning systems, and value-added formulations.',
    'blackGarlic.card4.title': 'Transparent Technical Framing',
    'blackGarlic.card4.desc': 'Research and nutrition sections are presented as reference-oriented information, avoiding exaggerated therapeutic claims while retaining process and composition clarity.',

    // ─── Black Garlic — About ──────────────────────────────────────
    'about.badge': 'What It Is',
    'about.title': 'Black Garlic',
    'about.p1': 'Black garlic is produced by holding whole garlic bulbs at controlled temperature and humidity for several weeks. The process triggers the Maillard reaction — a chemical transformation that darkens the cloves, softens their texture, and develops a flavor profile closer to balsamic or tamarind than raw garlic.',
    'about.p2': 'The fermentation process increases concentrations of S-allyl-cysteine (SAC), a water-soluble organosulfur compound, while reducing the allicin responsible for raw garlic\'s sharp bite. The result is a milder, more complex ingredient with a studied biochemical profile.',
    'about.p3': 'First developed commercially in Korea in the early 2000s, black garlic has since been adopted across professional kitchens and studied in nutritional research for its composition and bioactive compound content.',

    // ─── Black Garlic — Hero ───────────────────────────────────────
    'hero.badge': 'Fermented Garlic — Single Ingredient',
    'hero.title': 'Black Garlic',
    'hero.subtitle': 'Slow-Fermented. Naturally Transformed.',
    'hero.description': 'Whole garlic bulbs, fermented under controlled heat and humidity over several weeks. No additives. No shortcuts. The result is a product with a distinct flavor profile and a studied nutritional composition.',
    'hero.cta': 'Explore the Science',
    'hero.stat1.value': '2x',
    'hero.stat1.label': 'Antioxidant Markers',
    'hero.stat2.value': '30+',
    'hero.stat2.label': 'Days Fermented',
    'hero.stat3.value': '100%',
    'hero.stat3.label': 'Natural Process',

    // ─── Research ──────────────────────────────────────────────────
    'research.badge': 'Published Research',
    'research.title': 'Scientific Literature',
    'research.subtitle': 'Black garlic has been examined across multiple peer-reviewed studies. Findings vary by fermentation conditions, source material, and methodology — results should be interpreted in context.',
    'citation1.title': 'Antioxidant Activity',
    'citation1.finding': 'Laboratory analyses consistently show higher antioxidant marker readings in black garlic versus fresh garlic. The degree of increase varies by fermentation duration, temperature, and measurement method.',
    'citation1.source': 'Journal of Food Science, 2009',
    'citation1.doi': 'DOI: 10.1111/j.1750-3841.2009.01090.x',
    'citation2.title': 'Cardiovascular Markers',
    'citation2.finding': 'Controlled studies have observed improvements in LDL cholesterol and blood pressure in subjects supplementing with black garlic extract. Sample sizes are modest and further trials are warranted.',
    'citation2.source': 'Nutrition Research, 2014',
    'citation2.doi': 'DOI: 10.1016/j.nutres.2014.04.003',
    'citation3.title': 'Anti-Inflammatory Pathways',
    'citation3.finding': 'S-allyl-cysteine has shown measurable influence on inflammatory markers in cell culture studies. In vivo human data remains limited but directionally consistent.',
    'citation3.source': 'Molecules, 2017',
    'citation3.doi': 'DOI: 10.3390/molecules22060919',
    'citation4.title': 'Neuroprotective Properties',
    'citation4.finding': 'Animal model and cell culture studies suggest SAC may support neuronal protection under oxidative stress conditions. Human clinical data is preliminary.',
    'citation4.source': 'Neurochemical Research, 2018',
    'citation4.doi': 'DOI: 10.1007/s11064-018-2628-1',
    'citation5.title': 'Immune Modulation',
    'citation5.finding': 'Studies examining immune cell response to black garlic extract have shown measurable modulation in controlled settings. Population-level effects require broader clinical investigation.',
    'citation5.source': 'Clinical Nutrition, 2012',
    'citation5.doi': 'DOI: 10.1016/j.clnu.2012.01.002',
    'citation6.title': 'Cell-Level Studies',
    'citation6.finding': 'In vitro studies across multiple cell types have identified interactions with oxidative stress pathways. These findings inform ongoing research but do not constitute clinical claims.',
    'citation6.source': 'Food Chemistry, 2016',
    'citation6.doi': 'DOI: 10.1016/j.foodchem.2016.03.106',

    // ─── Benefits ──────────────────────────────────────────────────
    'benefits.badge': 'Studied Properties',
    'benefits.title': 'What the Research Examines',
    'benefits.subtitle': 'Bioactive properties identified in peer-reviewed literature. Composition varies by fermentation conditions.',
    'benefit1.title': 'Antioxidant Compounds',
    'benefit1.desc': 'Measurably higher antioxidant marker activity than fresh garlic across multiple laboratory analyses.',
    'benefit2.title': 'Cardiovascular Research',
    'benefit2.desc': 'Studies have examined effects on LDL cholesterol and blood pressure with directionally positive findings.',
    'benefit3.title': 'Digestive Tolerance',
    'benefit3.desc': 'Reduced allicin content makes black garlic significantly gentler on the digestive system than raw garlic.',
    'benefit4.title': 'Immune Research',
    'benefit4.desc': 'Controlled studies have examined immune cell response to black garlic extract with measurable findings.',
    'benefit5.title': 'S-Allyl-Cysteine',
    'benefit5.desc': 'Fermentation increases SAC concentration — a water-soluble organosulfur compound with an established research profile.',
    'benefit6.title': 'Anti-Inflammatory Studies',
    'benefit6.desc': 'Cell-level studies show influence on inflammatory pathways. Human clinical trials are ongoing.',

    // ─── Why Us ────────────────────────────────────────────────────
    'whyUs.badge': 'Our Approach',
    'whyUs.title': 'How We Make It',
    'whyUs.subtitle': 'Process discipline over volume. Consistency over shortcuts.',
    'whyUs.item1.title': 'Controlled Fermentation',
    'whyUs.item1.desc': 'Each batch is fermented under monitored temperature and humidity conditions for the full required duration. No acceleration.',
    'whyUs.item2.title': 'Single Ingredient',
    'whyUs.item2.desc': 'Whole garlic bulbs only. No additives, preservatives, or processing aids of any kind.',
    'whyUs.item3.title': 'Batch Inspection',
    'whyUs.item3.desc': 'Every batch is checked for color, texture, and consistency before it leaves the facility.',
    'whyUs.item4.title': 'Traceable Sourcing',
    'whyUs.item4.desc': 'Garlic is sourced from local regional growers and selected for variety and maturity suitability.',

    // ─── Nutrition ─────────────────────────────────────────────────
    'nutrition.badge': 'Composition',
    'nutrition.title': 'Nutritional Profile',
    'nutrition.subtitle': 'Approximate values per 100g. Actual composition varies by fermentation duration, temperature, and source variety.',
    'nutrition.note': 'Data compiled from multiple published analyses. Values are directional — exact figures vary significantly across batches and studies.',

    // ─── Black Garlic — Process ────────────────────────────────────
    'process.badge': 'Fermentation Process',
    'process.title': 'How Black Garlic Is Made',
    'process.subtitle': 'A slow, single-ingredient process. Temperature and humidity controlled throughout.',
    'bg.process.step1.title': 'Bulb Selection',
    'bg.process.step1.desc': 'Whole garlic bulbs are selected for size uniformity, skin integrity, and sugar content — all of which influence fermentation outcome.',
    'bg.process.step2.title': 'Chamber Preparation',
    'bg.process.step2.desc': 'Bulbs are placed in fermentation chambers calibrated to 80–90% relative humidity before the heat cycle begins.',
    'bg.process.step3.title': 'Fermentation',
    'bg.process.step3.desc': 'Held at 60–80°C for 30–40 days. The Maillard reaction and enzymatic activity transform the cloves — darkening color, softening texture, developing flavor.',
    'bg.process.step4.title': 'Inspection and Packaging',
    'bg.process.step4.desc': 'Finished bulbs are assessed for color uniformity and texture before packaging. No additives are introduced at any stage.',

    // ─── Comparison ────────────────────────────────────────────────
    'comparison.badge': 'Black vs Fresh',
    'comparison.title': 'How They Differ',
    'comparison.subtitle': 'Directional changes observed during fermentation. Exact values vary across studies and source material.',
    'comparison.nutrient': 'Component',
    'comparison.blackGarlic': 'Black Garlic',
    'comparison.freshGarlic': 'Fresh Garlic',
    'comparison.change': 'Direction',
    'comparison.lower': 'Reduced',
    'comparison.sac': 'S-Allyl-Cysteine',
    'comparison.polyphenols': 'Polyphenols',
    'comparison.antioxidant': 'Antioxidant Markers',
    'comparison.calories': 'Calories',
    'comparison.sugar': 'Natural Sugars',
    'comparison.allicin': 'Allicin',
    'comparison.note': 'Directional indicators only. Exact values vary significantly across batches, source material, and fermentation conditions.',

    // ─── Recipes ───────────────────────────────────────────────────
    'recipes.badge': 'In the Kitchen',
    'recipes.title': 'Culinary Applications',
    'recipes.subtitle': 'Black garlic works across a wide range of applications — from condiments to glazes. Its mellow sweetness integrates without overpowering.',
    'recipes.ingredients': 'Key Ingredients',
    'recipes.minutes': 'min',
    'recipes.servings': 'servings',
    'recipes.easy': 'Easy',
    'recipes.medium': 'Medium',
    'recipes.hard': 'Advanced',
    'recipe1.name': 'Black Garlic Aioli',
    'recipe1.description': 'A rich, umami-forward aioli. Works as a spread, a dip, or a finishing sauce for grilled meats and roasted vegetables.',
    'recipe1.ingredients': 'Black garlic, egg yolks, olive oil, lemon juice, Dijon mustard',
    'recipe2.name': 'Black Garlic Pasta',
    'recipe2.description': 'Simple pasta dressed with black garlic, good olive oil, and aged Parmesan. The garlic melts into the sauce rather than asserting itself.',
    'recipe2.ingredients': 'Spaghetti, black garlic, pancetta, Parmesan, olive oil, fresh herbs',
    'recipe3.name': 'Black Garlic Butter',
    'recipe3.description': 'Compound butter with black garlic and thyme. Finishes steaks cleanly, works on bread, dissolves into pasta.',
    'recipe3.ingredients': 'Unsalted butter, black garlic, fresh thyme, sea salt',
    'recipe4.name': 'Black Garlic Glazed Salmon',
    'recipe4.description': 'Pan-seared salmon with a black garlic and honey glaze. The glaze caramelizes without bitterness.',
    'recipe4.ingredients': 'Salmon fillet, black garlic, honey, soy sauce, ginger, sesame oil',

'products.blackGarlic.name': 'Black Garlic',
'products.blackGarlic.method': 'Controlled fermentation 30-40 days',
'products.blackGarlic.formats': 'Whole bulbs, peeled cloves, bulk',
'products.peeled.name': 'Peeled Frozen Garlic',
'products.peeled.method': 'Mechanical peeling, washing, centrifugal drying',
'products.peeled.formats': 'Chilled bulk, ambient retail packs',
'products.freeze.name': 'Freeze Dried Products',
'products.freeze.method': 'Sublimation drying at low temperature',
'products.freeze.formats': 'Granules, powder, flakes, slices',
'products.vacuum.name': 'Vacuum Fried Products',
'products.vacuum.method': 'Low-pressure frying below 120°C',
'products.vacuum.formats': 'Plain, seasoned, private label',
'products.roasted.name': 'Roasted Masala Garlic',
'products.roasted.method': 'Controlled roasting with masala coating',
'products.roasted.formats': 'Snack pouches, jars, bulk foodservice',

'contact.badge': 'Get In Touch',
'contact.title1': 'Contact &',
'contact.title2': 'Location',
'contact.subtitle': 'For bulk enquiries, trade partnerships, or product information — reach us directly.',
'contact.address.title': 'Address',
'contact.phone.title': 'Mobile',
'contact.email.title': 'Email',

'footer.tagline': 'Shubham Foods Products',
'footer.desc': 'Committed to delivering consistent quality, authentic taste, and carefully processed food products.',
'footer.rights': '© 2026 Shubham Foods. All rights reserved.',

'b2b.badge': 'Enquiry',
'b2b.title': 'Bulk and Trade Enquiries',
'b2b.subtitle': 'One form for both consumer and trade requests. Select enquiry type for the right level of detail.',
'b2b.inquiryType': 'Enquiry Type',
'b2b.consumer': 'Consumer',
'b2b.bulk': 'Bulk / B2B',
'b2b.contactName': 'Contact Name',
'b2b.contactName.placeholder': 'Your name',
'b2b.contactNumber': 'Contact Number',
'b2b.contactNumber.placeholder': 'Phone / WhatsApp',
'b2b.email': 'Email',
'b2b.location': 'Location',
'b2b.location.placeholder': 'City, State',
'b2b.companyName': 'Company Name',
'b2b.companyName.placeholder': 'Registered business name',
'b2b.businessType': 'Business Type',
'b2b.distributor': 'Distributor',
'b2b.exporter': 'Exporter',
'b2b.horeca': 'Horeca',
'b2b.retail': 'Retail',
'b2b.other': 'Other',
'b2b.products': 'Products of Interest',
'b2b.products.placeholder': 'Black Garlic, Peeled Garlic, Freeze Dried...',
'b2b.quantity': 'Estimated Monthly Quantity',
'b2b.quantity.placeholder': 'e.g. 500 kg / month',
'b2b.message': 'Message',
'b2b.message.bulk.placeholder': 'Share product specs, quantity expectations and delivery timeline.',
'b2b.message.consumer.placeholder': 'Let us know how we can help.',
'b2b.submit': 'Send Enquiry',

    // ─── FAQ ───────────────────────────────────────────────────────
    'faq.badge': 'Common Questions',
    'faq.title': 'FAQ',
    'faq.subtitle': 'Storage, usage, taste, and sourcing — answered directly.',
    'faq.storage.question': 'How should black garlic be stored?',
    'faq.storage.answer': 'Unopened, store in a cool dry place away from direct light. Once opened, refrigerate and use within 2–3 months. Whole bulbs keep at room temperature for up to 30 days. Individual cloves can be frozen for up to 12 months without significant quality loss.',
    'faq.usage.question': 'How is black garlic used in cooking?',
    'faq.usage.answer': 'It can be used raw or cooked. Mash into sauces, dressings, and compound butters. Add to pasta, pizza, or risotto. Use as a glaze base for proteins. Its sweetness and depth work in both savory and sweet applications — it does not overpower the way raw garlic does.',
    'faq.taste.question': 'What does black garlic taste like?',
    'faq.taste.answer': 'Sweet, tangy, and savory — with notes of balsamic, tamarind, and molasses. None of the sharpness or bite of raw garlic. The texture is soft and spreadable, similar to a dried fig.',
    'faq.safety.question': 'Is black garlic safe for everyone?',
    'faq.safety.answer': 'Generally yes — it is gentler on digestion than raw garlic. Those on anticoagulant medication should consult a physician, as garlic products can enhance blood-thinning effects. Consume in moderation during pregnancy.',
    'faq.purchasing.question': 'What should I look for when buying black garlic?',
    'faq.purchasing.answer': 'Uniformly dark, glossy cloves with no white spots or visible mold. Texture should be soft but not mushy. Fermentation duration matters — 30–40 days produces optimal results. Avoid products that do not disclose fermentation time or source.',
    'faq.shelfLife.question': 'How long does black garlic last?',
    'faq.shelfLife.answer': 'Commercially packaged and unopened: 12–24 months. Once opened: up to 3 months refrigerated. Spoilage indicators are off odors and visible mold. When in doubt, discard.',


    // ─── Peeled Garlic Page ────────────────────────────────────────
    'peeled.badge': 'Garlic Ingredients',
    'peeled.title1': 'Peeled',
    'peeled.title2': 'Frozen Garlic',
    'peeled.description': 'Clean, consistently processed peeled garlic cloves ready for horeca kitchens, food processors, and bulk repackers requiring reliable garlic inputs at scale.',
    'peeled.howMade.title': "How It's Made",
    'peeled.howMade.subtitle': 'After the shared garlic processing pipeline, peeled garlic goes through final grading and packaging steps.',
    'peeled.specs.title': 'Product Specifications',
    'peeled.step1.title': 'Post-Pipeline Entry',
    'peeled.step1.desc': 'Cloves arrive from the shared processing line — washed, centrifugally dried, colour sorted, and manually inspected.',
    'peeled.step2.title': 'Grade Separation',
    'peeled.step2.desc': 'Cloves are separated by size and visual grade to meet customer specifications for uniformity.',
    'peeled.step3.title': 'Chilling or Ambient Hold',
    'peeled.step3.desc': 'Depending on dispatch protocol, cloves are either chilled to near-zero or held at controlled ambient temperature.',
    'peeled.step4.title': 'Packaging',
    'peeled.step4.desc': 'Packed in food-grade pouches or bulk cartons as per buyer requirement — retail, horeca, or processor formats.',
    'peeled.spec1.label': 'Storage',
    'peeled.spec1.value': '0–4°C chilled or ambient',
    'peeled.spec2.label': 'Shelf Life',
    'peeled.spec2.value': 'Up to 12 months frozen',
    'peeled.spec3.label': 'Pack Formats',
    'peeled.spec3.value': 'Bulk cartons, retail pouches',
    'peeled.spec4.label': 'MOQ',
    'peeled.spec4.value': 'Negotiable — B2B enquiry',
    'peeled.spec5.label': 'Quality',
    'peeled.spec5.value': 'Colour sorted + manually inspected',
    'peeled.spec6.label': 'Suitable For',
    'peeled.spec6.value': 'Horeca, processors, repackers',

    // ─── Freeze Dried Page ─────────────────────────────────────────
    'freeze.badge': 'Dehydrated Products',
    'freeze.title1': 'Freeze',
    'freeze.title2': 'Dried Products',
    'freeze.description': 'Low-temperature sublimation drying that preserves flavor, color, and nutrition with ambient-stable shelf life — supplied as garlic and banana in multiple formats.',
    'freeze.variants.title': 'Product Variants',
    'freeze.howMade.title': "How It's Made",
    'freeze.howMade.subtitle': 'Freeze drying preserves what conventional drying destroys — flavor volatiles, cell structure, and nutritional density.',
    'freeze.specs.title': 'Product Specifications',
    'freeze.product1.name': 'Freeze Dried Garlic',
    'freeze.product1.desc': 'Concentrated garlic flavor in granule, powder, or flake form. Ideal for seasoning blends, instant foods, and food manufacturing.',
    'freeze.product2.name': 'Freeze Dried Banana',
    'freeze.product2.desc': 'Naturally sweet freeze dried banana slices and powder. Suitable for cereals, snack mixes, and health food applications.',
    'freeze.step1.title': 'Post-Pipeline Entry',
    'freeze.step1.desc': 'Peeled, washed, and inspected cloves enter the freeze-dry line after the shared processing pipeline.',
    'freeze.step2.title': 'Pre-Freezing',
    'freeze.step2.desc': 'Cloves or slices are rapidly frozen to lock cellular structure and preserve volatile flavor compounds.',
    'freeze.step3.title': 'Sublimation Drying',
    'freeze.step3.desc': 'Frozen product is placed in a vacuum chamber where ice converts directly to vapor — no liquid phase — retaining shape, color, and nutrition.',
    'freeze.step4.title': 'Milling and Sizing',
    'freeze.step4.desc': 'Dried product is milled into granules, powder, or flakes depending on buyer specification.',
    'freeze.step5.title': 'Moisture Check',
    'freeze.step5.desc': 'Final moisture content is verified per batch before packaging to ensure shelf stability.',
    'freeze.step6.title': 'Packaging',
    'freeze.step6.desc': 'Sealed in moisture-barrier pouches or bulk containers. Custom cuts and private label available.',
    'freeze.spec1.label': 'Storage',
    'freeze.spec1.value': 'Cool, dry — ambient stable',
    'freeze.spec2.label': 'Shelf Life',
    'freeze.spec2.value': 'Up to 24 months sealed',
    'freeze.spec3.label': 'Formats',
    'freeze.spec3.value': 'Granules, powder, flakes, slices',
    'freeze.spec4.label': 'MOQ',
    'freeze.spec4.value': 'Negotiable — B2B enquiry',
    'freeze.spec5.label': 'Quality',
    'freeze.spec5.value': 'Batch moisture verified',
    'freeze.spec6.label': 'Suitable For',
    'freeze.spec6.value': 'Seasoning, dry blends, retail',

    // ─── Vacuum Fried Page ─────────────────────────────────────────
    'vacuum.badge': 'Snack & Ingredient Line',
    'vacuum.title1': 'Vacuum',
    'vacuum.title2': 'Fried Products',
    'vacuum.description': 'Low-pressure frying that delivers crisp texture, vibrant color, and reduced oil content — across garlic, vegetables, and legumes for snack and ingredient applications.',
    'vacuum.range.title': 'Product Range',
    'vacuum.range.subtitle': 'Seven vacuum fried products across garlic, vegetables, legumes, and fruit.',
    'vacuum.howMade.title': "How It's Made",
    'vacuum.howMade.subtitle': 'Vacuum frying operates at significantly lower temperatures than conventional frying — protecting color, flavor, and nutritional value.',
    'vacuum.specs.title': 'Product Specifications',
    'vacuum.product1.name': 'Vacuum Fried Garlic',
    'vacuum.product1.desc': 'Crisp garlic chips with concentrated flavor. Lower oil content than conventional fried garlic.',
    'vacuum.product2.name': 'Vacuum Fried Okra',
    'vacuum.product2.desc': 'Delicate crunch with preserved green color. Popular in health-forward snack applications.',
    'vacuum.product3.name': 'Vacuum Fried Potatoes',
    'vacuum.product3.desc': 'Light, crisp potato slices with significantly reduced oil uptake versus standard frying.',
    'vacuum.product4.name': 'Vacuum Fried Chickpeas',
    'vacuum.product4.desc': 'High-protein snack base. Crisp texture suitable for seasoned and plain formats.',
    'vacuum.product5.name': 'Vacuum Fried Kidney Beans',
    'vacuum.product5.desc': 'Firm, crunchy texture. Suitable for trail mix, snack blends, and retail packs.',
    'vacuum.product6.name': 'Vacuum Fried Sweet Potatoes',
    'vacuum.product6.desc': 'Naturally sweet flavor profile with vibrant color retention from low-temperature frying.',
    'vacuum.product7.name': 'Vacuum Fried Banana',
    'vacuum.product7.desc': 'Crisp banana chips with natural sweetness. Available plain or lightly seasoned.',
    'vacuum.step1.title': 'Raw Material Preparation',
    'vacuum.step1.desc': 'Vegetables and legumes are cleaned, peeled where required, and cut to target dimensions for uniform frying.',
    'vacuum.step2.title': 'Blanching',
    'vacuum.step2.desc': 'Brief heat treatment deactivates enzymes that cause browning and off-flavors during frying.',
    'vacuum.step3.title': 'Vacuum Frying',
    'vacuum.step3.desc': 'Product is fried under low pressure — significantly reducing the boiling point of water and oil. This preserves color, nutrients, and creates a crisp texture with lower oil absorption than conventional frying.',
    'vacuum.step4.title': 'Centrifugal De-oiling',
    'vacuum.step4.desc': 'Excess surface oil is removed by centrifugal spinning immediately post-fry for a cleaner finish.',
    'vacuum.step5.title': 'Seasoning (Optional)',
    'vacuum.step5.desc': 'Plain or seasoned variants available. Spice blends applied under controlled tumbling for even coating.',
    'vacuum.step6.title': 'Packaging',
    'vacuum.step6.desc': 'Nitrogen-flushed packaging for extended shelf life. Bulk, retail, and private-label formats available.',
    'vacuum.spec1.label': 'Process Temp',
    'vacuum.spec1.value': 'Below 120°C vacuum frying',
    'vacuum.spec2.label': 'Shelf Life',
    'vacuum.spec2.value': 'Up to 12 months sealed',
    'vacuum.spec3.label': 'Formats',
    'vacuum.spec3.value': 'Plain, seasoned, private label',
    'vacuum.spec4.label': 'MOQ',
    'vacuum.spec4.value': 'Negotiable — B2B enquiry',
    'vacuum.spec5.label': 'Quality',
    'vacuum.spec5.value': 'Batch oil and moisture checks',
    'vacuum.spec6.label': 'Suitable For',
    'vacuum.spec6.value': 'Snack retail, horeca, export',

    // ─── Roasted Masala Page ───────────────────────────────────────
    'roasted.badge': 'Flavored Snack Line',
    'roasted.title1': 'Roasted',
    'roasted.title2': 'Masala Garlic',
    'roasted.description': 'Whole roasted garlic cloves with controlled masala coating — developed for retail snacking, gifting formats, and foodservice applications requiring a bold, ready-to-eat garlic product.',
    'roasted.highlights.title': 'Product Highlights',
    'roasted.howMade.title': "How It's Made",
    'roasted.howMade.subtitle': 'Roasting and masala coating are carried out in controlled batches to ensure consistency across flavor, texture, and appearance.',
    'roasted.specs.title': 'Product Specifications',
    'roasted.highlight1.title': 'Custom Spice Profiles',
    'roasted.highlight1.desc': 'Spice intensity and blend composition can be adjusted per channel — mild for retail, bold for foodservice.',
    'roasted.highlight2.title': 'Private Label Ready',
    'roasted.highlight2.desc': 'Supplied unbranded for repackers and private label buyers. Custom pack sizes and formats on request.',
    'roasted.highlight3.title': 'Snack & Ingredient Use',
    'roasted.highlight3.desc': 'Suitable as a ready-to-eat snack or as a flavored garlic ingredient for food manufacturing applications.',
    'roasted.step1.title': 'Post-Pipeline Entry',
    'roasted.step1.desc': 'Peeled, washed, and inspected cloves enter the roasting line after the shared garlic processing pipeline.',
    'roasted.step2.title': 'Roasting',
    'roasted.step2.desc': 'Cloves are roasted in controlled batches to develop the characteristic caramelized flavor profile without burning or uneven browning.',
    'roasted.step3.title': 'Cooling',
    'roasted.step3.desc': 'Roasted cloves are cooled rapidly to halt carryover cooking and stabilize texture before coating.',
    'roasted.step4.title': 'Masala Blending',
    'roasted.step4.desc': 'Spice blends are prepared in-house. Intensity and composition are adjustable per buyer specification.',
    'roasted.step5.title': 'Coating',
    'roasted.step5.desc': 'Masala is applied under controlled tumbling to ensure even, consistent coating across all cloves.',
    'roasted.step6.title': 'Packaging',
    'roasted.step6.desc': 'Packed in snack pouches, jars, or foodservice bulk formats. Private label and custom spice profiles available.',
    'roasted.spec1.label': 'Storage',
    'roasted.spec1.value': 'Cool, dry — ambient stable',
    'roasted.spec2.label': 'Shelf Life',
    'roasted.spec2.value': 'Up to 9 months sealed',
    'roasted.spec3.label': 'Formats',
    'roasted.spec3.value': 'Snack pouches, jars, bulk',
    'roasted.spec4.label': 'MOQ',
    'roasted.spec4.value': 'Negotiable — B2B enquiry',
    'roasted.spec5.label': 'Quality',
    'roasted.spec5.value': 'Batch roast + coating checks',
    'roasted.spec6.label': 'Suitable For',
    'roasted.spec6.value': 'Retail snack, gifting, horeca',
  },

  // ════════════════════════════════════════════════════════════════
  // GUJARATI
  // ════════════════════════════════════════════════════════════════
  gu: {
    'nav.about': 'વિશે',
    'nav.science': 'વિજ્ઞાન',
    'nav.benefits': 'ફાયદા',
    'nav.nutrition': 'પોષણ',
    'nav.process': 'પ્રક્રિયા',
    'nav.comparison': 'સરખામણી',
    'nav.recipes': 'વાનગીઓ',
    'nav.faq': 'FAQ',
    'nav.home': 'હોમ',
    'nav.blackGarlic': 'કાળું લસણ',
    'nav.peeledGarlic': 'છોલેલું લસણ',
    'nav.freezeDried': 'ફ્રીઝ ડ્રાઈડ',
    'nav.vacuumFried': 'વેક્યૂમ ફ્રાઈડ',
    'nav.roastedMasala': 'રોસ્ટેડ મસાલા',
    'nav.b2b': 'B2B',
    'nav.contact': 'સંપર્ક',
    'nav.subtitle': 'લસણ ઉત્પાદ ઉત્પાદક',
    
    'home.hero.title': 'ખેતરથી તૈયાર ખાદ્ય ઉત્પાદનો સુધી',
    'home.hero.description': 'શુભમ ફૂડ્સ એ મૂલ્ય-વર્ધિત લસણ પ્રક્રિયા એકમ છે, જે જથ્થાબંધ અને છૂટક બજારો માટે સુસ્થિત, ગુણવત્તા-નિયંત્રિત ઉત્પાદનો પૂરા પાડે છે.',
    'home.hero.cta.products': 'ઉત્પાદો જુઓ',
    'home.hero.cta.enquiry': 'જથ્થાબંધ પૂછપરછ',
    
    'intro.badge': 'ગુજરાત, ભારત',
    'intro.heading1': 'એક સુવિધા.',
    'intro.heading2': 'પાંચ ઉત્પાદ',
    'intro.heading3': 'લાઇન. સ્થિર ઉત્પાદન.',
    'intro.p1': 'શુભમ ફૂડ્સ ઊભી રીતે સંકલિત લસણ પ્રક્રિયા સુવિધા ચલાવે છે — સ્થાનિક સ્ત્રોતના કાચા બલ્બોથી દસ-તબક્કાની પ્રક્રિયા પાઇપલાઇન દ્વારા પાંચ અલગ ઉત્પાદ શ્રેણીઓ સુધી.',
    'intro.p2': 'દરેક ઉત્પાદ લાઇન સ્થિર, ટ્રેસ થઈ શકે તેવા ઉત્પાદન માટે રંગ-વર્ગીકરણ, સેન્ટ્રિફ્યૂગલ ડ્રાઈંગ અને મેન્યુઅલ ઇન્સ્પેક્શન જેવી ગુણવત્તા નિયંત્રણ પ્રક્રિયાઓ વહેંચે છે.',
    'intro.stat1.value': '૧૦+',
    'intro.stat1.label': 'પ્રક્રિયા તબક્કા',
    'intro.stat2.value': '૫',
    'intro.stat2.label': 'ઉત્પાદ લાઇન',
    'intro.stat3.value': 'B2B',
    'intro.stat3.label': 'જથ્થાબંધ તૈયાર',
    
    'intro.products.label': 'ઉત્પાદ લાઇન',
    'intro.line1.label': 'કાળું લસણ',
    'intro.line1.sub': 'આથવણ • પ્રીમિયમ',
    'intro.line2.label': 'છોલેલું ફ્રોઝન લસણ',
    'intro.line2.sub': 'ઘટક • જથ્થાબંધ',
    'intro.line3.label': 'ફ્રીઝ ડ્રાઈડ',
    'intro.line3.sub': 'લસણ અને કેળા',
    'intro.line4.label': 'વેક્યૂમ ફ્રાઈડ',
    'intro.line4.sub': '૭ પ્રકાર',
    'intro.line5.label': 'રોસ્ટેડ મસાલા',
    'intro.line5.sub': 'નાસ્તો • છૂટક',
    
    'about.company.badge': 'શુભમ ફૂડ્સ વિશે',
    'about.company.title': 'પ્રક્રિયા-કેન્દ્રિત ખાદ્ય ઉત્પાદન',
    'about.company.subtitle': 'અમે ઇનપુટ ગુણવત્તા, પ્રક્રિયા નિયંત્રણ અને ઉત્પાદ શ્રેણીઓ પ્રત્યે ભરોસાપાત્ર ઉત્પાદન પર વ્યવહારિક ધ્યાન સાથે મૂલ્ય-વૃદ્ધિ પ્રક્રિયા કંપની તરીકે કાર્ય કરીએ છીએ.',
    'about.company.point1.title': 'સ્થાનિક સ્ત્રોત નેટવર્ક',
    'about.company.point1.desc': 'અમે વિવિધતા, પ્રૌઢતા અને પ્રક્રિયા યોગ્યતાના આધારે પ્રાદેશિક ઉત્પાદકો પાસેથી લસણ મેળવીએ છીએ.',
    'about.company.point2.title': 'યાંત્રિક અને મેન્યુઅલ પ્રક્રિયા',
    'about.company.point2.desc': 'અમારી લાઇન સૉર્ટિંગ અને ગુણવત્તા ચકાસણી માટેના મુખ્ય બિંદુઓ પર મેન્યુઅલ ચેક સાથે ઉપકરણ-સ્થિરતા જોડે છે.',
    'about.company.point3.title': 'વિસ્તરણ-તૈયાર ઇન્ફ્રાસ્ટ્રક્ચર',
    'about.company.point3.desc': 'સુવિધા પ્રક્રિયા શિસ્ત સાથે સમાધાન કર્યા વિના બૅચ સ્કેલ કરવા અને મલ્ટી-ઉત્પાદ ઓપરેશન્સ સ‌પોર્ટ કરવા સ્થાપિત છે.',
    'about.company.point4.title': 'બહુ ઉત્પાદ ફોર્મેટ',
    'about.company.point4.desc': 'કાચા અને છોલેલાથી આથવેલા અને તળેલા ફોર્મેટ સુધી, અમે લસણને રાંધણ, છૂટક અને ઔદ્યોગિક ઉપયોગ માટે ઉત્પાદોમાં પ્રક્રિયા કરીએ છીએ.',
    
    'process.company.badge': 'કંપની કાર્યપ્રવાહ',
    'process.company.title': 'ઉત્પાદ લાઇન્સ વ્યાપ પ્રક્રિયા પ્રવાહ',
    'process.company.subtitle': 'અંતિમ પૅકેજિંગ અથવા લાઇન-વિશિષ્ટ મૂલ્ય-વૃદ્ધિ પહેલાં, સહિયારા પ્રક્રિયા તબક્કા એક સ્ટ્રક્ચર્ડ સિસ્ટમ તરીકે સંચાલિત છે.',
    'process.step1.title': 'સ્થાનિક સ્ત્રોત',
    'process.step1.desc': 'ગુણવત્તા અને ઋતુ આધારિત સ્થાનિક સ્ત્રોત ક્લસ્ટર્સમાંથી લસણ પ્રાપ્ત થાય છે.',
    'process.step2.title': 'સૂર્ય સૂકવણી',
    'process.step2.desc': 'નિયંત્રિત સૂર્ય સૂકવણી દ્વારા પ્રારંભિક ભેજ સંતુલન.',
    'process.step3.title': 'ટ્રે સૂકવણી',
    'process.step3.desc': 'સમાન નિયંત્રિત નિર્જળીકરણ માટે ઉત્પાદ ટ્રે ડ્રાયર્સમાં ખસેડાય છે.',
    'process.step4.title': 'બલ્બ બ્રેકર',
    'process.step4.desc': 'ડાઉનસ્ટ્રીમ પ્રક્રિયા માટે બલ્બ યાંત્રિક રીતે અલગ કરાય છે.',
    'process.step5.title': 'છોલવું',
    'process.step5.desc': 'ઉપકરણ અને મેન્યુઅલ લાઇન ચેક દ્વારા છોલવાની પ્રક્રિયા.',
    'process.step6.title': 'ધોવું',
    'process.step6.desc': 'સપાટીની અશુદ્ધિઓ અને ઢીલા અવશેષો દૂર કરવા ક્લોવ્સ ધોવાય છે.',
    'process.step7.title': 'સેન્ટ્રિફ્યૂગલ સૂકવણી',
    'process.step7.desc': 'ધોયેલ સામગ્રી લક્ષ્ય સપાટી ભેજ સ્તર સુધી સૂકવાય છે.',
    'process.step8.title': 'રંગ વર્ગીકરણ',
    'process.step8.desc': 'દેખાવ સુસંગતતા માટે ઓપ્ટિકલ અને વિઝ્યુઅલ સૉર્ટિંગ.',
    'process.step9.title': 'મેન્યુઅલ સૉર્ટિંગ',
    'process.step9.desc': 'ખામીઓ અને બિન-અનુરૂપ ટુકડા દૂર કરવા અંતિમ હસ્ત સૉર્ટિંગ.',
    'process.step10.title': 'પૅકેજિંગ અથવા વધુ પ્રક્રિયા',
    'process.step10.desc': 'લૉટ પૅક કરાય છે અથવા આથવણ, રોસ્ટિંગ, ફ્રીઝ ડ્રાઈંગ અથવા વેક્યૂમ ફ્રાઈંગ લાઇન્સ પર ખસેડાય છે.',
    
    'products.badge': 'ઉત્પાદ અવલોકન',
    'products.title': 'શુભમ ફૂડ્સ ઉત્પાદ લાઇન',
    'products.subtitle': 'સહિયારી ગુણવત્તા-નિયંત્રિત પાઇપલાઇન પર નિર્મિત પાંચ પ્રક્રિયા લાઇન.',
    'products.viewDetails': 'વિગત જુઓ',
    
    'productDetails.peeled.name': 'છોલેલું લસણ',
    'productDetails.peeled.p1': 'બલ્બ બ્રેકર, છોલવું, ધોવું અને નિયંત્રિત સેન્ટ્રિફ્યૂગલ ડ્રાઈંગ દ્વારા પ્રક્રિયા.',
    'productDetails.peeled.p2': 'સ્વચ્છ લસણ ઇનપુટ્સ જોઈતા હૉરેકા કિચન, પ્રૉસેસર્સ અને રીપૅકર્સ માટે યોગ્ય.',
    'productDetails.peeled.p3': 'હૅન્ડલિંગ પ્રૉટોકૉલ અનુસાર ચિલ્ડ અથવા ઍમ્બિઅન્ટ-કૉમ્પૅટિબલ પૅક્સમાં સ‌પ્લાય.',
    
    'productDetails.freeze.name': 'ફ્રીઝ ડ્રાઈડ ઉત્પાદ',
    'productDetails.freeze.p1': 'સ્વાદ, રંગ અને પોષણ જોખમ ઓછું કરી ઓછા તાપમાને ભેજ દૂર કરવો.',
    'productDetails.freeze.p2': 'સીઝનિંગ અને ડ્રાય બ્લૅન્ડ ઉપયોગ માટે ગ્રૅન્યૂલ્સ, પૉઉડર અને ફ્લૅક્સ.',
    'productDetails.freeze.p3': 'ભેજ અને કણ સુસંગતતા માટે બૅચ-સ્તર ચેક.',
    
    'productDetails.vacuum.name': 'વેક્યૂમ ફ્રાઈડ ઉત્પાદ',
    'productDetails.vacuum.p1': 'વેક્યૂમ ફ્રાઈંગ સામાન્ય ફ્રાઈંગ કરતાં ઓછા થર્મલ સ્ટ્રૅસ પર ક્રિસ્પ ટૅક્સ્ચર આપે છે.',
    'productDetails.vacuum.p2': 'સ્નૅક અને ઘટક ઉપયોગ માટે પ્લૅઇન અથવા સીઝ્ડ સ‌પ્લાય.',
    'productDetails.vacuum.p3': 'સ્થિર આઉટ‌પુટ માટે ઑઇલ ગુણવત્તા અને પોસ્ટ-ફ્રાય હૅન્ડલિંગ નિયંત્રિત.',
    
    'productDetails.roasted.name': 'રોસ્ટેડ મસાલા લસણ',
    'productDetails.roasted.p1': 'નિયંત્રિત મસાલા બ્લૅન્ડિંગ અને કોટિંગ સાથે ઇન્ટિગ્રેટેડ રોસ્ટેડ લસણ.',
    'productDetails.roasted.p2': 'રેડી-ટૂ-ઇટ સ્નૅકિંગ અને ફ્લૅવર-ફૉર્વર્ડ રીટેઇલ ઉત્પાદ માટે.',
    'productDetails.roasted.p3': 'ચૅનલ-વિશિષ્ટ જરૂરિયાત માટે કસ્ટમ મસાલા તીવ્રતા અને પૅક સાઇઝ.',
    
    'blackGarlic.badge': 'શુભમ ફૂડ્સનો ઉત્પાદ',
    'blackGarlic.title': 'કાળું લસણ',
    'blackGarlic.subtitle': 'કાળું લસણ સંપૂર્ણ ગાંઠોના નિયંત્રિત ફર્મેન્ટેશન દ્વારા બનાવવામાં આવે છે, જેના પરિણામે મીઠો અને નરમ સ્વાદ પ્રોફાઇલ મળે છે જે રસોઈમાં મૂલ્યવાન માનવામાં આવે છે.',
    'blackGarlic.card1.title': 'નિયંત્રિત આથવણ',
    'blackGarlic.card1.desc': 'દરેક બેચ માટે તાપમાન, ભેજ અને સમયગાળાનું સંચાલન કરવામાં આવે છે જેથી રચના, રંગ અને સ્વાદની સતત પ્રગતિ પ્રાપ્ત થાય.',
    'blackGarlic.card2.title': 'રાંધણ મૂલ્ય',
    'blackGarlic.card2.desc': 'આ ઉત્પાદનમાં ઉમામી ઊંડાઈ, પ્રાકૃતિક મીઠાશ અને ઓછી તીવ્રતા મળે છે — જે સોસ, મેરિનેડ, કન્ડિમેન્ટ અને પ્રીમિયમ તૈયાર-ખાવા ફોર્મેટમાં ઉપયોગી છે.',
    'blackGarlic.card3.title': 'પ્રક્રિયા ઉપયોગિતા',
    'blackGarlic.card3.desc': 'કાળું લસણ સીધી રસોઈ માટે અથવા મિશ્રણ, સ્પ્રેડ, સીઝનિંગ સિસ્ટમ અને મૂલ્યવર્ધિત ફોર્મ્યુલેશન માટે ઘટક તરીકે પૂરૂં પાડવામાં આવી શકે છે.',
    'blackGarlic.card4.title': 'પારદર્શક ટેક્નિકલ ફ્રેમિંગ',
    'blackGarlic.card4.desc': 'સંશોધન અને પોષણ વિભાગો સંદર્ભ આધારિત માહિતી તરીકે રજૂ કરવામાં આવ્યા છે.',
    
    'about.badge': 'આ શું છે',
    'about.title': 'કાળું લસણ',
    'about.p1': 'કાળા લસણને સંપૂર્ણ લસણના ગાંઠોને નિયંત્રિત તાપમાન અને ભેજ હેઠળ અનેક અઠવાડિયા સુધી રાખીને બનાવવામાં આવે છે. આ પ્રક્રિયા માયાર્ડ પ્રતિક્રિયાને પ્રેરિત કરે છે — જેમાં કળી ગાઢ રંગની બને છે, રચના નરમ થાય છે અને કાચા લસણની તુલનામાં બાલ્સામિક અને ઇમલી જેવી સ્વાદ પ્રોફાઇલ વિકસે છે.',
    'about.p2': 'ફર્મેન્ટેશન પ્રક્રિયા S-એલાઇલ-સિસ્ટેઇન (SAC) — એક પાણીમાં દ્રાવ્ય ઓર્ગેનોસલ્ફર સંયોજન — ની સાંદ્રતા વધારશે, જ્યારે કાચા લસણની તીવ્રતા માટે જવાબદાર એલિસિન ઘટે છે.',
    'about.p3': '2000ના પ્રારંભિક દાયકામાં કોરિયામાં વ્યાવસાયિક રીતે વિકસાવવામાં આવેલ કાળું લસણ ત્યારથી વ્યાવસાયિક રસોડાં અને પોષણ સંશોધનમાં અપનાવવામાં આવ્યું છે.',
    
    'hero.badge': 'આથવેલું લસણ — એક ઘટક',
    'hero.title': 'કાળું લસણ',
    'hero.subtitle': 'ધીરે આથવેલું. કુદરતી રૂપે પરિવર્તિત.',
    'hero.description': 'સંપૂર્ણ લસણના ગાંઠો નિયંત્રિત ગરમી અને ભેજ હેઠળ 30-40 દિવસ સુધી ફર્મેન્ટ કરવામાં આવે છે. કોઈ ઉમેરણ નહીં. કોઈ શોર્ટકટ નહીં. એક જ ઘટક, સંપૂર્ણ રૂપાંતરિત.',
    'hero.cta': 'વિજ્ઞાન જાણો',
    'hero.stat1.value': '2x',
    'hero.stat1.label': 'એન્ટિઑક્સિડૅન્ટ માર્કર',
    'hero.stat2.value': '30+',
    'hero.stat2.label': 'દિવસ આથવ્યા',
    'hero.stat3.value': '100%',
    'hero.stat3.label': 'પ્રાકૃતિક પ્રક્રિયા',
    
    'research.badge': 'પ્રકાશિત સંશોધન',
    'research.title': 'વૈજ્ઞાનિક સાહિત્ય',
    'research.subtitle': 'કાળા લસણ પર અનેક પિયર-રીવ્યૂ અભ્યાસોમાં તપાસ કરવામાં આવી છે. પરિણામો ફર્મેન્ટેશન પરિસ્થિતિઓ, મૂળ સામગ્રી અને પદ્ધતિ મુજબ બદલાય છે.',
    
    'benefits.badge': 'અભ્યાસ કરેલ ગુણધર્મો',
    'benefits.title': 'સંશોધન શું તપાસે છે',
    'benefits.subtitle': 'પિયર-રીવ્યૂ સાહિત્યમાં ઓળખાયેલી બાયોએક્ટિવ ગુણધર્મો.',
    
    'nutrition.badge': 'રચના',
    'nutrition.title': 'પોષણ પ્રોફાઇલ',
    'nutrition.subtitle': 'દર 100 ગ્રામ માટે અંદાજિત મૂલ્યો. વાસ્તવિક રચના ફર્મેન્ટેશન સમયગાળા, તાપમાન અને મૂળ જાતિ પ્રમાણે બદલાય છે.',
    'nutrition.note': 'ડેટા પસંદ કરાયેલા પ્રકાશિત વિશ્લેષણોમાંથી સંકલિત. મૂલ્યો દિશાત્મક છે — ચોક્કસ આંકડા બેચ અને અભ્યાસ પ્રમાણે નોંધપાત્ર રીતે બદલાય છે.',
    
    'comparison.badge': 'કાળું અને તાજું',
    'comparison.title': 'તેઓ કેવી રીતે અલગ છે',
    'comparison.subtitle': 'ફર્મેન્ટેશન દરમિયાન જોવા મળેલા દિશાત્મક ફેરફારો. ચોક્કસ આંકડા અભ્યાસ અને મૂળ સામગ્રી મુજબ બદલાય છે.',
    'comparison.note': 'માત્ર દિશાત્મક સૂચકો. ચોક્કસ આંકડા બેચ, મૂળ સામગ્રી અને ફર્મેન્ટેશન પરિસ્થિતિઓ અનુસાર નોંધપાત્ર રીતે બદલાય છે.',
    
    'recipes.badge': 'રસોડામાં',
    'recipes.title': 'પાકકળા ઉપયોગો',
    'recipes.subtitle': 'કાળું લસણ કન્ડિમેન્ટથી લઈને ગ્લેઝ સુધી અનેક ઉપયોગોમાં કામ કરે છે.',
    'recipes.ingredients': 'મુખ્ય ઘટકો',
    'recipes.easy': 'સરળ',
    'recipes.medium': 'મધ્યમ',
    'recipes.hard': 'ઉન્નત',
    
    'faq.badge': 'સામાન્ય પ્રશ્નો',
    'faq.title': 'FAQ',
    'faq.subtitle': 'સંગ્રહ, ઉપયોગ, સ્વાદ અને ખરીદી — સીધા જવાબ.',
    
    'footer.tagline': 'શુભમ ફૂડ્સ ઉત્પાદ',
    'footer.desc': 'સ્થિર ગુણવત્તા, અધિકૃત સ્વાદ અને કાળજીપૂર્વક પ્રક્રિયા કરેલ ખાદ્ય ઉત્પાદ પૂરા પાડવા પ્રતિબદ્ધ.',
    'footer.address': 'ઝાડેશ્વર ગ્રામ પંચાયત પાસે, ઝાડેશ્વર, જિ. ભરૂચ (ગુજરાત)',
    'footer.disclaimer': 'સંશોધન સંદર્ભો માહિતી માટે છે. આ તબીબી સલાહ નથી.',
'products.peeled.name': 'છોલેલું જમેલું લસણ',
'products.peeled.method': 'યાંત્રિક છોલવું, ધોવું, સેન્ટ્રિફ્યૂગલ સૂકવણી',
'products.peeled.formats': 'ઠંડુ જથ્થાબંધ, આસપાસના તાપમાને રિટેલ પેક',
'products.freeze.name': 'ફ્રીઝ ડ્રાઈડ ઉત્પાદ',
'products.freeze.method': 'ઓછા તાપમાને સબ્લિમેશન સુકવણી',
'products.freeze.formats': 'ગ્રેન્યુલ, પાવડર, ફ્લેક, સ્લાઇસ',
'products.vacuum.name': 'વેક્યૂમ ફ્રાઈડ ઉત્પાદ',
'products.vacuum.method': '120°C થી નીચે ઓછા દબાણ હેઠળ તળવું',
'products.vacuum.formats': 'સાદું, મસાલેદાર, પ્રાઇવેટ લેબલ',
'products.roasted.name': 'રોસ્ટેડ મસાલા લસણ',
'products.roasted.method': 'મસાલા કોટિંગ સાથે નિયંત્રિત રોસ્ટિંગ',
'products.roasted.formats': 'સ્નેક પાઉચ, જાર, જથ્થાબંધ ફૂડસર્વિસ',
'products.blackGarlic.name': 'કાળું લસણ',
'products.blackGarlic.method': '30-40 દિવસ નિયંત્રિત ફર્મેન્ટેશન',
'products.blackGarlic.formats': 'સંપૂર્ણ ગાંઠો, છોલેલી કળીઓ, જથ્થાબંધ',

'b2b.badge': 'પૂછપરછ',
'b2b.title': 'જથ્થાબંધ અને વ્યાપાર પૂછપરછ',
'b2b.subtitle': 'ગ્રાહક અને વ્યાપાર બંને વિનંતીઓ માટે એક ફોર્મ. યોગ્ય સ્તરની માહિતી માટે પૂછપરછ પ્રકાર પસંદ કરો.',
'b2b.inquiryType': 'પૂછપરછ પ્રકાર',
'b2b.consumer': 'ગ્રાહક',
'b2b.bulk': 'જથ્થાબંધ / B2B',
'b2b.contactName': 'સંપર્ક નામ',
'b2b.contactName.placeholder': 'તમારું નામ',
'b2b.contactNumber': 'સંપર્ક નંબર',
'b2b.contactNumber.placeholder': 'ફોન / WhatsApp',
'b2b.email': 'ઇમેઇલ',
'b2b.location': 'સ્થાન',
'b2b.location.placeholder': 'શહેર, રાજ્ય',
'b2b.companyName': 'કંપની નામ',
'b2b.companyName.placeholder': 'નોંધાયેલ વ્યાપાર નામ',
'b2b.businessType': 'વ્યાપાર પ્રકાર',
'b2b.distributor': 'વિતરક',
'b2b.exporter': 'નિકાસકાર',
'b2b.horeca': 'હોરેકા',
'b2b.retail': 'રિટેલ',
'b2b.other': 'અન્ય',
'b2b.products': 'રુચિના ઉત્પાદ',
'b2b.products.placeholder': 'કાળું લસણ, છોલેલું લસણ, ફ્રીઝ ડ્રાઈડ...',
'b2b.quantity': 'અંદાજિત માસિક જથ્થો',
'b2b.quantity.placeholder': 'દા.ત. 500 કિ.ગ્રા. / મહિનો',
'b2b.message': 'સંદેશ',
'b2b.message.bulk.placeholder': 'ઉત્પાદ વિશિષ્ટતાઓ, જથ્થાની અપેક્ષા અને ડિલિવરી સમયરેખા શેર કરો.',
'b2b.message.consumer.placeholder': 'અમે કેવી રીતે મદદ કરી શકીએ તે જણાવો.',
'b2b.submit': 'પૂછપરછ મોકલો',

//─── PEELED GARLIC ───────────────────────────────────────
'peeled.badge': 'લસણ ઘટકો',
'peeled.title1': 'છોલેલું',
'peeled.title2': 'ફ્રોઝન લસણ',
'peeled.description': 'સ્વચ્છ અને સતત પ્રક્રિયા કરેલી છોલેલી લસણની કળીઓ — હોટેલ-રેસ્ટોરાં-કેટરિંગ રસોડા, ખાદ્ય પ્રક્રિયાકારો અને મોટા પ્રમાણમાં રિ-પેકર્સ માટે.',
'peeled.howMade.title': 'કેવી રીતે બને છે',
'peeled.howMade.subtitle': 'સહિયારી લસણ પ્રક્રિયા પાઈપલાઈન પછી, છોલેલું લસણ અંતિમ ગ્રેડિંગ અને પેકેજિંગ તબક્કામાંથી પસાર થાય છે.',
'peeled.specs.title': 'ઉત્પાદન વિશિષ્ટતાઓ',
'peeled.step1.title': 'પાઈપલાઈન પ્રવેશ',
'peeled.step1.desc': 'કળીઓ સહિયારી પ્રક્રિયા લાઈનમાંથી આવે છે — ધોવાયેલી, સેન્ટ્રિફ્યુગલ ડ્રાઈ, રંગ-સૉર્ટ અને હાથ-તપાસ થયેલ.',
'peeled.step2.title': 'ગ્રેડ વિભાજન',
'peeled.step2.desc': 'ગ્રાહકની સ્પષ્ટતા અનુસાર એકરૂપતા માટે કળીઓ કદ અને દ્રશ્ય ગ્રેડ પ્રમાણે અલગ કરવામાં આવે છે.',
'peeled.step3.title': 'ઠંડક અથવા એમ્બિઅન્ટ હોલ્ડ',
'peeled.step3.desc': 'ડિસ્પેચ પ્રોટોકોલ મુજબ, કળીઓ નજીક-શૂન્ય ઠંડી કરવામાં આવે છે અથવા નિયંત્રિત એમ્બિઅન્ટ તાપમાને રાખવામાં આવે છે.',
'peeled.step4.title': 'પેકેજિંગ',
'peeled.step4.desc': 'ખરીદનારની જરૂરિયાત પ્રમાણે ફૂડ-ગ્રેડ પાઉચ અથવા બલ્ક કાર્ટનમાં પેક — રિટેઈલ, હોરેકા અથવા પ્રોસેસર ફોર્મેટ.',
'peeled.spec1.label': 'સ્ટોરેજ',
'peeled.spec1.value': '0-4°C ઠંડું અથવા એમ્બિઅન્ટ',
'peeled.spec2.label': 'શેલ્ફ લાઈફ',
'peeled.spec2.value': 'ફ્રોઝન 12 મહિના સુધી',
'peeled.spec3.label': 'પેક ફોર્મેટ',
'peeled.spec3.value': 'બલ્ક કાર્ટન, રિટેઈલ પાઉચ',
'peeled.spec4.label': 'MOQ',
'peeled.spec4.value': 'ચર્ચાપાત્ર — B2B પૂછપરછ',
'peeled.spec5.label': 'ગુણવત્તા',
'peeled.spec5.value': 'રંગ-સૉર્ટ + હાથ-તપાસ',
'peeled.spec6.label': 'ઉપયુક્ત',
'peeled.spec6.value': 'હોરેકા, પ્રોસેસર, રિ-પેકર',

//─── FREEZE DRIED ────────────────────────────────────────
'freeze.badge': 'ડિહાઈડ્રેટેડ ઉત્પાદનો',
'freeze.title1': 'ફ્રીઝ',
'freeze.title2': 'ડ્રાઈડ પ્રોડક્ટ્સ',
'freeze.description': 'નીચા તાપમાને સ્બ્લિમેશન ડ્રાઈંગ — સ્વાદ, રંગ અને પોષણ સાચવીને — એમ્બિઅન્ટ-સ્ટેબલ શેલ્ફ લાઈફ સાથે.',
'freeze.variants.title': 'ઉત્પાદ વ્યવહારો',
'freeze.howMade.title': 'કેવી રીતે બને છે',
'freeze.howMade.subtitle': 'ફ્રીઝ ડ્રાઈંગ તે સાચવે છે જે પ્રચલિત ડ્રાઈંગ નષ્ટ કરે છે — સ્વાદ, કોષ-રચના અને પોષક ઘનત્વ.',
'freeze.specs.title': 'ઉત્પાદન વિશિષ્ટતાઓ',
'freeze.product1.name': 'ફ્રીઝ ડ્રાઈડ લસણ',
'freeze.product1.desc': 'ગ્રેન્યુલ, પાઉડર અથવા ફ્લેક સ્વરૂપે કેન્દ્રિત લસણ સ્વાદ. સીઝનિંગ બ્લેન્ડ, ઇન્સ્ટન્ટ ખોરાક અને ફૂડ મેન્યુફેક્ચરિંગ માટે આદર્શ.',
'freeze.product2.name': 'ફ્રીઝ ડ્રાઈડ કેળું',
'freeze.product2.desc': 'કુદરતી રીતે મીઠા ફ્રીઝ ડ્રાઈડ કેળાના સ્લાઈસ અને પાઉડર. અનાજ, સ્નેક મિક્સ અને હેલ્થ ફૂડ એપ્લિકેશન માટે.',
'freeze.step1.title': 'પાઈપલાઈન પ્રવેશ',
'freeze.step1.desc': 'છોલેલી, ધોવાયેલી અને તપાસ થયેલ કળીઓ સહિયારી પ્રક્રિયા પાઈપ લાઈન પછી ફ્રીઝ-ડ્રાઈ લાઈનમાં પ્રવેશ કરે છે.',
'freeze.step2.title': 'પ્રી-ફ્રીઝિંગ',
'freeze.step2.desc': 'કળીઓ અથવા સ્લાઈસ ઝડપથી ફ્રીઝ થાય છે — કોષ-રચના જાળવવા અને અસ્થિર સ્વાદ સંયોજનો સાચવવા.',
'freeze.step3.title': 'સ્બ્લિમેશન ડ્રાઈંગ',
'freeze.step3.desc': 'ફ્રોઝન ઉત્પાદ વેક્યૂમ ચેમ્બરમાં મૂકવામાં આવે છે જ્યાં બરફ સીધો વરાળ બને છે — કોઈ પ્રવાહી તબક્કો નહીં — આકાર, રંગ અને પોષણ સચવાય.',
'freeze.step4.title': 'મિલિંગ અને સાઈઝિંગ',
'freeze.step4.desc': 'ડ્રાઈ ઉત્પાદ ખરીદનારની સ્પષ્ટતા અનુસાર ગ્રેન્યુલ, પાઉડર અથવા ફ્લેકમાં મિલ થાય છે.',
'freeze.step5.title': 'ભેજ તપાસ',
'freeze.step5.desc': 'શેલ્ફ સ્થિરતા સુનિશ્ચિત કરવા પ્રત્યેક બેચ પેક થતાં પહેલાં અંતિમ ભેજ-સ્તર ચકાસવામાં આવે છે.',
'freeze.step6.title': 'પેકેજિંગ',
'freeze.step6.desc': 'ભેજ-અવરોધ પાઉચ અથવા બલ્ક કન્ટેઈનરમાં સીલ. કસ્ટમ કટ અને પ્રાઈવેટ લેબલ ઉપલબ્ધ.',
'freeze.spec1.label': 'સ્ટોરેજ',
'freeze.spec1.value': 'ઠંડું, સૂકું — એમ્બિઅન્ટ સ્ટેબલ',
'freeze.spec2.label': 'શેલ્ફ લાઈફ',
'freeze.spec2.value': 'સીલ 24 મહિના સુધી',
'freeze.spec3.label': 'ફોર્મેટ',
'freeze.spec3.value': 'ગ્રેન્યુલ, પાઉડર, ફ્લેક, સ્લાઈસ',
'freeze.spec4.label': 'MOQ',
'freeze.spec4.value': 'ચર્ચાપાત્ર — B2B પૂછપરછ',
'freeze.spec5.label': 'ગુણવત્તા',
'freeze.spec5.value': 'બેચ ભેજ ચકાસ',
'freeze.spec6.label': 'ઉપયુક્ત',
'freeze.spec6.value': 'સીઝનિંગ, ડ્રાય બ્લેન્ડ, રિટેઈલ',

'vacuum.badge': 'નાસ્તા ઘટકો',
'vacuum.title1': 'વેક્યૂમ ફ્રાઈડ',
'vacuum.title2': 'ઉત્પાદ',
'vacuum.description': 'ઓછા તાપમાને વેક્યૂમ ફ્રાઈંગ રંગ, સ્વાદ અને પોષક તત્વોને પરંપરાગત તળવાની તુલનામાં વધુ સારી રીતે જાળવે છે — સ્વચ્છ લેબલવાળા નાસ્તા અને ઘટકો બનાવે છે.',
'vacuum.step1.title': 'કાચા માલની પસંદગી',
'vacuum.step1.desc': 'સતત તળવાના પરિણામો માટે તાજું લસણ, કેળા અને અન્ય ઉત્પાદ ગ્રેડ મુજબ પસંદ કરવામાં આવે છે.',
'vacuum.step2.title': 'તૈયારી અને કાપવું',
'vacuum.step2.desc': 'ઉત્પાદનને સાફ કરીને, છોલીને અને સમાન જાડાઈમાં કાપવામાં આવે છે જેથી સમાન રીતે તળી શકાય.',
'vacuum.step3.title': 'વેક્યૂમ ચેમ્બર તળવું',
'vacuum.step3.desc': 'વેક્યૂમ દબાણ હેઠળ 120°C થી ઓછા તાપમાને તળવામાં આવે છે, જેથી તેલનું શોષણ ઓછું થાય અને પોષક તત્વો જળવાય.',
'vacuum.step4.title': 'તેલ સેન્ટ્રિફ્યૂગિંગ',
'vacuum.step4.desc': 'હળવા અને સ્વચ્છ ઉત્પાદ માટે તળ્યા પછી તરત જ સેન્ટ્રિફ્યૂજ દ્વારા વધારાનું તેલ દૂર કરવામાં આવે છે.',
'vacuum.step5.title': 'મસાલેદાર બનાવવું (વૈકલ્પિક)',
'vacuum.step5.desc': 'તેલ દૂર કર્યા પછી સાદા અથવા મસાલેદાર વિકલ્પોને જરૂરિયાત મુજબ કોટ કરવામાં આવે છે.',
'vacuum.step6.title': 'પેકેજિંગ',
'vacuum.step6.desc': 'કરકરોપણું અને શેલ્ફ લાઇફ જાળવવા નાઇટ્રોજન-ફ્લશ્ડ ભેજ-રોધક પાઉચમાં સીલ કરવામાં આવે છે.',
'vacuum.spec1.label': 'પ્રક્રિયા તાપમાન',
'vacuum.spec1.value': 'વેક્યૂમ હેઠળ 120°C થી નીચે',
'vacuum.spec2.label': 'શેલ્ફ લાઇફ',
'vacuum.spec2.value': '12 મહિના સુધી',
'vacuum.spec3.label': 'ફોર્મેટ',
'vacuum.spec3.value': 'સાદું, મસાલેદાર, પ્રાઇવેટ લેબલ',
'vacuum.spec4.label': 'ન્યૂનતમ ઓર્ડર જથ્થો',
'vacuum.spec4.value': 'વાટાઘાટયોગ્ય — B2B પૂછપરછ',
'vacuum.spec5.label': 'તેલનું પ્રમાણ',
'vacuum.spec5.value': 'પરંપરાગત તળવાની તુલનામાં ઓછું',
'vacuum.spec6.label': 'યોગ્ય માટે',
'vacuum.spec6.value': 'સ્નેક બ્રાન્ડ, હોરેકા, રિટેલ',
'vacuum.product1.name': 'વેક્યૂમ ફ્રાઈડ લસણ ફ્લેક્સ',
'vacuum.product1.desc': 'કરકરા સુવર્ણ લસણ ફ્લેક્સ. સ્વચ્છ લસણ સ્વાદ, ઓછું તેલ.',
'vacuum.product2.name': 'વેક્યૂમ ફ્રાઈડ લસણ ચિપ્સ',
'vacuum.product2.desc': 'સંપૂર્ણ સ્લાઇસ ચિપ્સ. ગાર્નિશ અને સ્નેક ફોર્મેટ માટે આદર્શ.',
'vacuum.product3.name': 'વેક્યૂમ ફ્રાઈડ કેળા ચિપ્સ',
'vacuum.product3.desc': 'પ્રાકૃતિક મીઠાશ સાથે હલકી અને કરકરી કેળાની ચિપ્સ.',
'vacuum.product4.name': 'વેક્યૂમ ફ્રાઈડ બેબી કોર્ન',
'vacuum.product4.desc': 'નરમ બેબી કોર્ન, હળવેથી તળેલું. કરકરો નાસ્તો અથવા સલાડ ટોપિંગ.',
'vacuum.product5.name': 'વેક્યૂમ ફ્રાઈડ કારેલા',
'vacuum.product5.desc': 'સંતુલિત સ્વાદવાળા કારેલા ચિપ્સ, વેક્યૂમ પ્રક્રિયા કડવાશ ઘટાડે છે.',
'vacuum.product6.name': 'વેક્યૂમ ફ્રાઈડ બટાકા ચિપ્સ',
'vacuum.product6.desc': 'ઓછા તાપમાને બનેલા ક્લાસિક બટાકા ચિપ્સ, સ્વચ્છ લેબલ માટે યોગ્ય.',
'vacuum.product7.name': 'વેક્યૂમ ફ્રાઈડ મશરૂમ',
'vacuum.product7.desc': 'માટી જેવા સ્વાદવાળા મશરૂમ ચિપ્સ. ઊંચી સ્વાદ તીવ્રતા, ઓછું તેલ.',
'vacuum.range.title': 'ઉત્પાદ શ્રેણી',
'vacuum.range.subtitle': 'લસણ, શાકભાજી અને ફળ કેટેગરીમાં સાત વેક્યૂમ ફ્રાઈડ ઉત્પાદ.',
'vacuum.howMade.title': 'કેવી રીતે બનાવાય છે',
'vacuum.howMade.subtitle': '120°C થી નીચે વેક્યૂમ ફ્રાઈંગનો અર્થ ઓછું તેલ, વધુ સારો રંગ અને પરંપરાગત તળવાની તુલનામાં જળવાયેલા પોષક તત્વો.',
'vacuum.specs.title': 'ઉત્પાદ વિશિષ્ટતાઓ',

'roasted.badge': 'સ્વાદિષ્ટ લસણ',
'roasted.title1': 'રોસ્ટેડ',
'roasted.title2': 'મસાલા લસણ',
'roasted.description': 'મસાલા કોટિંગ સાથે રોસ્ટ કરેલી સંપૂર્ણ છોલેલી લસણ કળીઓ — તૈયાર-ખાવા નાસ્તો અને સ્વાદિષ્ટ ઘટક.',
'roasted.step1.title': 'કળીઓની પસંદગી',
'roasted.step1.desc': 'સાંઝા પાઇપલાઇનમાંથી છોલેલી કળીઓ પસંદ કરી અને રોસ્ટિંગ પહેલાં કદની સમાનતા માટે ગ્રેડ કરવામાં આવે છે.',
'roasted.step2.title': 'મસાલા કોટિંગ',
'roasted.step2.desc': 'કળીઓને મીઠું, મરચું, જીરું અને વિશિષ્ટ મસાલા મિશ્રણ સાથે કોટ કરવામાં આવે છે.',
'roasted.step3.title': 'નિયંત્રિત રોસ્ટિંગ',
'roasted.step3.desc': 'મસાલા બળ્યા વગર અને કળી વધુ નરમ થયા વગર સ્વાદ વિકસાવવા નિયંત્રિત તાપમાને રોસ્ટ કરવામાં આવે છે.',
'roasted.step4.title': 'ઠંડુ કરવું',
'roasted.step4.desc': 'કરકરોપણું જાળવવા અને મસાલા કોટિંગ સેટ કરવા ટ્રે પર ઠંડુ કરવામાં આવે છે.',
'roasted.step5.title': 'ગુણવત્તા તપાસ',
'roasted.step5.desc': 'પેકેજિંગ પહેલાં દૃશ્ય અને સ્વાદ તપાસ. ગેરમાનક કળીઓ દૂર કરવામાં આવે છે.',
'roasted.step6.title': 'પેકેજિંગ',
'roasted.step6.desc': 'ઓર્ડર મુજબ રિટેલ સ્નેક પાઉચ, જાર અથવા જથ્થાબંધ ફૂડસર્વિસ ફોર્મેટમાં પેક કરવામાં આવે છે.',
'roasted.spec1.label': 'સંગ્રહ',
'roasted.spec1.value': 'ઠંડુ, સુકું, આસપાસનું તાપમાન',
'roasted.spec2.label': 'શેલ્ફ લાઇફ',
'roasted.spec2.value': '9 મહિના સુધી',
'roasted.spec3.label': 'ફોર્મેટ',
'roasted.spec3.value': 'સ્નેક પાઉચ, જાર, જથ્થાબંધ',
'roasted.spec4.label': 'ન્યૂનતમ ઓર્ડર જથ્થો',
'roasted.spec4.value': 'વાટાઘાટયોગ્ય — B2B પૂછપરછ',
'roasted.spec5.label': 'કોટિંગ',
'roasted.spec5.value': 'મસાલા મિશ્રણ',
'roasted.spec6.label': 'યોગ્ય માટે',
'roasted.spec6.value': 'રિટેલ નાસ્તા, ગિફ્ટિંગ, હોરેકા',
'roasted.highlight1.title': 'તિવ્ર સ્વાદ',
'roasted.highlight1.desc': 'સંતુલિત તીખાશ, મીઠું અને મસાલા માટે વિકસાવેલું વિશિષ્ટ મસાલા મિશ્રણ.',
'roasted.highlight2.title': 'સંપૂર્ણ કળી રચના',
'roasted.highlight2.desc': 'કુદરતી લસણ સ્વાદ ગુમાવ્યા વગર સંતોષકારક ટેક્સચર જાળવવા રોસ્ટ કરવામાં આવ્યું છે.',
'roasted.highlight3.title': 'બહુમુખી ફોર્મેટ',
'roasted.highlight3.desc': 'અલગ નાસ્તા તરીકે, ગાર્નિશ તરીકે અથવા રસોઈમાં સ્વાદિષ્ટ ઘટક તરીકે ઉપયોગી.',
'roasted.highlights.title': 'ઉત્પાદ વિશેષતાઓ',
'roasted.howMade.title': 'કેવી રીતે બનાવાય છે',
'roasted.howMade.subtitle': 'સાંઝા લસણ પાઇપલાઇનથી શરૂ કરીને, રોસ્ટેડ મસાલા લસણમાં સ્વાદ અને રોસ્ટિંગ તબક્કો ઉમેરવામાં આવે છે જેથી અંતિમ ગ્રાહક ઉત્પાદ મળે.',
'roasted.specs.title': 'ઉત્પાદ વિશિષ્ટતાઓ',

'contact.badge': 'સંપર્ક કરો',
'contact.title1': 'સંપર્ક અને',
'contact.title2': 'સ્થાન',
'contact.subtitle': 'જથ્થાબંધ પૂછપરછ, વ્યાપાર ભાગીદારી અથવા ઉત્પાદ માહિતી માટે — અમારો સીધો સંપર્ક કરો.',
'contact.address.title': 'સરનામું',
'contact.phone.title': 'મોબાઇલ',
'contact.email.title': 'ઇમેઇલ',
    'footer.rights': '© ૨૦૨૬ શુભમ ફૂડ્સ. સર્વ હક્ક સુરક્ષિત.',
    },
    
  // HINDI
  // ════════════════════════════════════════════════════════════════
  hi: {
    // ─── Navigation ───────────────────────────────────────────────
    'nav.about': 'हमारे बारे में',
    'nav.science': 'विज्ञान',
    'nav.benefits': 'फायदे',
    'nav.nutrition': 'पोषण',
    'nav.process': 'प्रक्रिया',
    'nav.comparison': 'तुलना',
    'nav.recipes': 'व्यंजन',
    'nav.faq': 'FAQ',
    'nav.home': 'होम',
    'nav.blackGarlic': 'काला लहसुन',
    'nav.peeledGarlic': 'छिला लहसुन',
    'nav.freezeDried': 'फ्रीज़ ड्राइड',
    'nav.vacuumFried': 'वैक्यूम फ्राइड',
    'nav.roastedMasala': 'रोस्टेड मसाला',
    'nav.b2b': 'B2B',
    'nav.contact': 'संपर्क',
    'nav.subtitle': 'लहसुन उत्पाद निर्माता',

    // ─── Hero (Home) ───────────────────────────────────────────────
    'home.hero.title': 'खेत से तैयार खाद्य उत्पादों तक',
    'home.hero.description': 'शुभम फूड्स एक मूल्य-वर्धित लहसुन प्रसंस्करण इकाई है जो थोक और खुदरा बाज़ारों के लिए सुसंगत, गुणवत्ता-नियंत्रित उत्पाद प्रदान करती है।',
    'home.hero.cta.products': 'उत्पाद देखें',
    'home.hero.cta.enquiry': 'थोक पूछताछ',

    // ─── Intro Section ─────────────────────────────────────────────
    'intro.badge': 'गुजरात, भारत',
    'intro.heading1': 'एक सुविधा।',
    'intro.heading2': 'पांच उत्पाद',
    'intro.heading3': 'लाइनें। सुसंगत उत्पादन।',
    'intro.p1': 'शुभम फूड्स एक लंबवत एकीकृत लहसुन प्रसंस्करण सुविधा संचालित करता है — स्थानीय स्रोत के कच्चे बल्बों से दस-चरणीय प्रसंस्करण पाइपलाइन के माध्यम से पांच अलग-अलग श्रेणियों में तैयार उत्पादों तक।',
    'intro.p2': 'हर उत्पाद लाइन सुसंगत, ट्रेस करने योग्य उत्पादन के लिए समान अपस्ट्रीम गुणवत्ता नियंत्रण — रंग-छंटाई, केन्द्रापसारक सुखाना, और मैन्युअल निरीक्षण — साझा करती है।',
    'intro.stat1.value': '१०+',
    'intro.stat1.label': 'प्रसंस्करण चरण',
    'intro.stat2.value': '५',
    'intro.stat2.label': 'उत्पाद लाइनें',
    'intro.stat3.value': 'B2B',
    'intro.stat3.label': 'थोक तैयार',
    'intro.products.label': 'उत्पाद लाइनें',
    'intro.line1.label': 'काला लहसुन',
    'intro.line1.sub': 'किण्वित • प्रीमियम',
    'intro.line2.label': 'छिला फ्रोज़न लहसुन',
    'intro.line2.sub': 'घटक • थोक',
    'intro.line3.label': 'फ्रीज़ ड्राइड',
    'intro.line3.sub': 'लहसुन और केला',
    'intro.line4.label': 'वैक्यूम फ्राइड',
    'intro.line4.sub': '७ किस्में',
    'intro.line5.label': 'रोस्टेड मसाला',
    'intro.line5.sub': 'स्नैक • खुदरा',

    // ─── Company About ─────────────────────────────────────────────
    'about.company.badge': 'शुभम फूड्स के बारे में',
    'about.company.title': 'प्रसंस्करण-केंद्रित खाद्य निर्माण',
    'about.company.subtitle': 'हम इनपुट गुणवत्ता, प्रक्रिया नियंत्रण, और उत्पाद श्रेणियों में विश्वसनीय उत्पादन पर व्यावहारिक ध्यान के साथ एक मूल्य-वर्धित प्रसंस्करण कंपनी के रूप में काम करते हैं।',
    'about.company.point1.title': 'स्थानीय सोर्सिंग नेटवर्क',
    'about.company.point1.desc': 'हम किस्म, परिपक्वता और प्रसंस्करण उपयुक्तता के आधार पर क्षेत्रीय उत्पादकों से लहसुन प्राप्त करते हैं।',
    'about.company.point2.title': 'यांत्रिक + मैन्युअल प्रसंस्करण',
    'about.company.point2.desc': 'हमारी लाइन छंटाई और गुणवत्ता सत्यापन के लिए प्रमुख बिंदुओं पर मैन्युअल जांच के साथ उपकरण-नेतृत्व वाली स्थिरता जोड़ती है।',
    'about.company.point3.title': 'विस्तार-तैयार बुनियादी ढांचा',
    'about.company.point3.desc': 'सुविधा प्रक्रिया अनुशासन से समझौता किए बिना बैच स्केल करने और मल्टी-प्रोडक्ट ऑपरेशन समर्थन के लिए स्थापित है।',
    'about.company.point4.title': 'एकाधिक उत्पाद प्रारूप',
    'about.company.point4.desc': 'कच्चे और छिले से किण्वित और तले हुए प्रारूपों तक, हम लहसुन को पाक, खुदरा और औद्योगिक उपयोग के लिए उत्पादों में प्रसंस्कृत करते हैं।',

    // ─── Process Section ───────────────────────────────────────────
    'process.company.badge': 'कंपनी कार्यप्रवाह',
    'process.company.title': 'उत्पाद लाइनों में प्रसंस्करण प्रवाह',
    'process.company.subtitle': 'साझा प्रसंस्करण चरणों को अंतिम पैकेजिंग या लाइन-विशिष्ट मूल्य संवर्धन से पहले एक संरचित प्रणाली के रूप में प्रबंधित किया जाता है।',
    'process.step1.title': 'स्थानीय सोर्सिंग',
    'process.step1.desc': 'लहसुन को गुणवत्ता और मौसम के आधार पर स्थानीय आपूर्ति क्लस्टर से प्राप्त किया जाता है।',
    'process.step2.title': 'धूप में सुखाना',
    'process.step2.desc': 'नियंत्रित धूप में सुखाने के माध्यम से प्रारंभिक नमी संतुलन किया जाता है।',
    'process.step3.title': 'ट्रे ड्रायिंग',
    'process.step3.desc': 'उत्पाद को समान नियंत्रित निर्जलीकरण के लिए ट्रे ड्रायर में स्थानांतरित किया जाता है।',
    'process.step4.title': 'बल्ब ब्रेकर',
    'process.step4.desc': 'बल्बों को डाउनस्ट्रीम प्रसंस्करण के लिए यांत्रिक रूप से अलग किया जाता है।',
    'process.step5.title': 'छीलना',
    'process.step5.desc': 'उपकरण और मैन्युअल लाइन जांच के माध्यम से छीलने का काम किया जाता है।',
    'process.step6.title': 'धुलाई',
    'process.step6.desc': 'सतह की अशुद्धियां और ढीले अवशेषों को हटाने के लिए लौंग धोए जाते हैं।',
    'process.step7.title': 'केन्द्रापसारक सुखाना',
    'process.step7.desc': 'धुले हुए सामग्री को लक्ष्य सतह नमी स्तर तक सुखाया जाता है।',
    'process.step8.title': 'रंग छंटाई',
    'process.step8.desc': 'उपस्थिति स्थिरता के लिए ऑप्टिकल और दृश्य छंटाई की जाती है।',
    'process.step9.title': 'मैन्युअल छंटाई',
    'process.step9.desc': 'अंतिम हाथ छंटाई दोष और गैर-अनुरूप टुकड़ों को हटाती है।',
    'process.step10.title': 'पैकेजिंग या आगे प्रसंस्करण',
    'process.step10.desc': 'लॉट पैक किए जाते हैं या किण्वन, रोस्टिंग, फ्रीज़ ड्रायिंग, या वैक्यूम फ्राइंग लाइनों में स्थानांतरित किए जाते हैं।',

    // ─── Products Overview ─────────────────────────────────────────
    'products.badge': 'उत्पाद अवलोकन',
    'products.title': 'शुभम फूड्स की उत्पाद लाइनें',
    'products.subtitle': 'साझा गुणवत्ता-नियंत्रित पाइपलाइन पर निर्मित पांच प्रसंस्करण लाइनें।',
    'products.viewDetails': 'विवरण देखें',

    // ─── Product Details (Home) ────────────────────────────────────
    'productDetails.peeled.name': 'छिला लहसुन',
    'productDetails.peeled.p1': 'बल्ब ब्रेकर, छीलने, धुलाई और नियंत्रित केन्द्रापसारक सुखाने के माध्यम से प्रसंस्कृत।',
    'productDetails.peeled.p2': 'साफ लहसुन इनपुट की आवश्यकता वाले होरेका रसोई, प्रोसेसर और रिपैकर के लिए उपयुक्त।',
    'productDetails.peeled.p3': 'हैंडलिंग प्रोटोकॉल के अनुसार ठंडा या परिवेश-संगत पैक में आपूर्ति।',
    'productDetails.freeze.name': 'फ्रीज़ ड्राइड उत्पाद',
    'productDetails.freeze.p1': 'केंद्रित स्वाद और बेहतर शेल्फ लाइफ के लिए कम तापमान पर नमी हटाना।',
    'productDetails.freeze.p2': 'मसाला और ड्राई ब्लेंड अनुप्रयोगों के लिए दाने, पाउडर और फ्लेक्स के रूप में उपलब्ध।',
    'productDetails.freeze.p3': 'नमी और कण स्थिरता के लिए बैच-स्तरीय जांच।',
    'productDetails.vacuum.name': 'वैक्यूम फ्राइड उत्पाद',
    'productDetails.vacuum.p1': 'वैक्यूम फ्राइंग पारंपरिक फ्राइंग की तुलना में कम थर्मल तनाव पर कुरकुरा बनावट का समर्थन करती है।',
    'productDetails.vacuum.p2': 'स्नैक और सामग्री उपयोग के लिए सादा या मसालेदार आपूर्ति की जा सकती है।',
    'productDetails.vacuum.p3': 'तेल गुणवत्ता और पोस्ट-फ्राय हैंडलिंग सुसंगत उत्पादन के लिए नियंत्रित।',
    'productDetails.roasted.name': 'रोस्टेड मसाला लहसुन',
    'productDetails.roasted.p1': 'नियंत्रित मसाला मिश्रण और कोटिंग के साथ एकीकृत रोस्टेड लहसुन।',
    'productDetails.roasted.p2': 'रेडी-टू-ईट स्नैकिंग और फ्लेवर-फॉरवर्ड खुदरा उत्पादों के लिए विकसित।',
    'productDetails.roasted.p3': 'चैनल-विशिष्ट आवश्यकताओं के लिए कस्टम मसाला तीव्रता और पैक आकार उपलब्ध।',

    // ─── Black Garlic Section ──────────────────────────────────────
    'blackGarlic.badge': 'शुभम फूड्स का एक उत्पाद',
    'blackGarlic.title': 'काला लहसुन',
    'blackGarlic.subtitle': 'काला लहसुन पूरे बल्बों के नियंत्रित किण्वन के माध्यम से उत्पादित होता है, जिसके परिणामस्वरूप पाक अनुप्रयोगों में मूल्यवान मीठा, हल्का प्रोफाइल मिलता है।',
    'blackGarlic.card1.title': 'नियंत्रित किण्वन',
    'blackGarlic.card1.desc': 'सुसंगत बनावट, रंग और स्वाद प्रगति देने के लिए तापमान, आर्द्रता और अवधि बैच दर बैच प्रबंधित की जाती है।',
    'blackGarlic.card2.title': 'पाक मूल्य',
    'blackGarlic.card2.desc': 'उत्पाद उमामी गहराई, प्राकृतिक मिठास और कम तीखापन प्रदान करता है, जिससे यह सॉस, मैरिनेड, मसालों और प्रीमियम रेडी-टू-ईट प्रारूपों में उपयोगी है।',
    'blackGarlic.card3.title': 'प्रसंस्करण उपयोगिता',
    'blackGarlic.card3.desc': 'काले लहसुन को सीधे पाक उपयोग के लिए या ब्लेंड, स्प्रेड, सीज़निंग सिस्टम और मूल्य-वर्धित फॉर्मूलेशन के इनपुट के रूप में आपूर्ति किया जा सकता है।',
    'blackGarlic.card4.title': 'पारदर्शी तकनीकी फ्रेमिंग',
    'blackGarlic.card4.desc': 'अनुसंधान और पोषण अनुभाग संदर्भ-उन्मुख जानकारी के रूप में प्रस्तुत किए जाते हैं।',

    // ─── Black Garlic — About ──────────────────────────────────────
    'about.badge': 'यह क्या है',
    'about.title': 'काला लहसुन',
    'about.p1': 'काला लहसुन पूरे लहसुन के बल्बों को कई हफ्तों तक नियंत्रित तापमान और आर्द्रता पर रखकर उत्पादित किया जाता है। यह प्रक्रिया मेलार्ड प्रतिक्रिया को ट्रिगर करती है — एक रासायनिक परिवर्तन जो लौंग को काला करता है, उनकी बनावट को नरम करता है, और कच्चे लहसुन की तुलना में बाल्सामिक या इमली के करीब एक स्वाद प्रोफाइल विकसित करता है।',
    'about.p2': 'किण्वन प्रक्रिया S-allyl-cysteine (SAC) की सांद्रता बढ़ाती है, एक जल-घुलनशील ऑर्गेनोसल्फर यौगिक, जबकि कच्चे लहसुन की तेज़ चुभन के लिए जिम्मेदार एलिसिन को कम करती है।',
    'about.p3': '2000 के दशक की शुरुआत में कोरिया में व्यावसायिक रूप से विकसित, काला लहसुन तब से पेशेवर रसोई और पोषण संबंधी शोध में अपनाया गया है।',

    // ─── Black Garlic — Hero ───────────────────────────────────────
    'hero.badge': 'किण्वित लहसुन — एकल सामग्री',
    'hero.title': 'काला लहसुन',
    'hero.subtitle': 'धीरे-धीरे किण्वित। प्राकृतिक रूप से परिवर्तित।',
    'hero.description': 'पूरे लहसुन के बल्ब, कई हफ्तों तक नियंत्रित गर्मी और आर्द्रता में किण्वित। कोई योजक नहीं। कोई शॉर्टकट नहीं।',
    'hero.cta': 'विज्ञान जानें',
    'hero.stat1.value': '2x',
    'hero.stat1.label': 'एंटीऑक्सीडेंट मार्कर',
    'hero.stat2.value': '30+',
    'hero.stat2.label': 'दिन किण्वित',
    'hero.stat3.value': '100%',
    'hero.stat3.label': 'प्राकृतिक प्रक्रिया',

    // ─── Research ──────────────────────────────────────────────────
    'research.badge': 'प्रकाशित शोध',
    'research.title': 'वैज्ञानिक साहित्य',
    'research.subtitle': 'काले लहसुन की कई सहकर्मी-समीक्षित अध्ययनों में जांच की गई है। निष्कर्ष किण्वन स्थितियों, स्रोत सामग्री और कार्यप्रणाली के अनुसार भिन्न होते हैं।',
    'citation1.title': 'एंटीऑक्सीडेंट गतिविधि',
    'citation1.finding': 'प्रयोगशाला विश्लेषण ताजे लहसुन की तुलना में काले लहसुन में उच्च एंटीऑक्सीडेंट मार्कर रीडिंग दिखाते हैं।',
    'citation1.source': 'Journal of Food Science, 2009',
    'citation1.doi': 'DOI: 10.1111/j.1750-3841.2009.01090.x',
    'citation2.title': 'हृदय संबंधी मार्कर',
    'citation2.finding': 'नियंत्रित अध्ययनों में काले लहसुन के अर्क के पूरक LDL कोलेस्ट्रॉल और रक्तचाप में सुधार देखा गया है।',
    'citation2.source': 'Nutrition Research, 2014',
    'citation2.doi': 'DOI: 10.1016/j.nutres.2014.04.003',
    'citation3.title': 'सूजन-रोधी मार्ग',
    'citation3.finding': 'S-allyl-cysteine ने कोशिका संस्कृति अध्ययनों में सूजन मार्करों पर मापने योग्य प्रभाव दिखाया है।',
    'citation3.source': 'Molecules, 2017',
    'citation3.doi': 'DOI: 10.3390/molecules22060919',
    'citation4.title': 'न्यूरोप्रोटेक्टिव गुण',
    'citation4.finding': 'पशु मॉडल और कोशिका संस्कृति अध्ययन बताते हैं कि SAC ऑक्सीडेटिव तनाव में न्यूरॉन्स की रक्षा कर सकता है।',
    'citation4.source': 'Neurochemical Research, 2018',
    'citation4.doi': 'DOI: 10.1007/s11064-018-2628-1',
    'citation5.title': 'प्रतिरक्षा नियंत्रण',
    'citation5.finding': 'काले लहसुन के अर्क के प्रति प्रतिरक्षा कोशिका प्रतिक्रिया की जांच करने वाले अध्ययनों ने नियंत्रित सेटिंग में मापने योग्य नियंत्रण दिखाया है।',
    'citation5.source': 'Clinical Nutrition, 2012',
    'citation5.doi': 'DOI: 10.1016/j.clnu.2012.01.002',
    'citation6.title': 'कोशिका-स्तरीय अध्ययन',
    'citation6.finding': 'कई कोशिका प्रकारों में इन विट्रो अध्ययनों ने ऑक्सीडेटिव तनाव मार्गों के साथ अंतःक्रिया की पहचान की है।',
    'citation6.source': 'Food Chemistry, 2016',
    'citation6.doi': 'DOI: 10.1016/j.foodchem.2016.03.106',

    // ─── Benefits ──────────────────────────────────────────────────
    'benefits.badge': 'अध्ययन किए गए गुण',
    'benefits.title': 'शोध क्या जांचता है',
    'benefits.subtitle': 'सहकर्मी-समीक्षित साहित्य में पहचाने गए जैव-सक्रिय गुण।',
    'benefit1.title': 'एंटीऑक्सीडेंट यौगिक',
    'benefit1.desc': 'ताजे लहसुन की तुलना में कई प्रयोगशाला विश्लेषणों में मापने योग्य उच्च एंटीऑक्सीडेंट मार्कर गतिविधि।',
    'benefit2.title': 'हृदय संबंधी शोध',
    'benefit2.desc': 'अध्ययनों ने LDL कोलेस्ट्रॉल और रक्तचाप पर सकारात्मक दिशात्मक निष्कर्षों के साथ प्रभावों की जांच की है।',
    'benefit3.title': 'पाचन सहनशीलता',
    'benefit3.desc': 'कम एलिसिन सामग्री काले लहसुन को कच्चे लहसुन की तुलना में पाचन तंत्र पर काफी हल्का बनाती है।',
    'benefit4.title': 'प्रतिरक्षा शोध',
    'benefit4.desc': 'नियंत्रित अध्ययनों ने मापने योग्य निष्कर्षों के साथ काले लहसुन के अर्क के प्रति प्रतिरक्षा कोशिका प्रतिक्रिया की जांच की है।',
    'benefit5.title': 'S-Allyl-Cysteine',
    'benefit5.desc': 'किण्वन SAC सांद्रता बढ़ाता है — एक स्थापित शोध प्रोफाइल वाला जल-घुलनशील ऑर्गेनोसल्फर यौगिक।',
    'benefit6.title': 'सूजन-रोधी अध्ययन',
    'benefit6.desc': 'कोशिका-स्तरीय अध्ययन सूजन मार्गों पर प्रभाव दिखाते हैं। मानव नैदानिक परीक्षण जारी हैं।',

    // ─── Why Us ────────────────────────────────────────────────────
    'whyUs.badge': 'हमारा दृष्टिकोण',
    'whyUs.title': 'हम इसे कैसे बनाते हैं',
    'whyUs.subtitle': 'मात्रा से अधिक प्रक्रिया अनुशासन। शॉर्टकट से अधिक स्थिरता।',
    'whyUs.item1.title': 'नियंत्रित किण्वन',
    'whyUs.item1.desc': 'प्रत्येक बैच को पूरी आवश्यक अवधि के लिए निगरानी किए गए तापमान और आर्द्रता की स्थिति में किण्वित किया जाता है।',
    'whyUs.item2.title': 'एकल सामग्री',
    'whyUs.item2.desc': 'केवल पूरे लहसुन के बल्ब। किसी भी प्रकार का कोई योजक, परिरक्षक या प्रसंस्करण सहायक नहीं।',
    'whyUs.item3.title': 'बैच निरीक्षण',
    'whyUs.item3.desc': 'सुविधा छोड़ने से पहले हर बैच की रंग, बनावट और स्थिरता के लिए जांच की जाती है।',
    'whyUs.item4.title': 'ट्रेसेबल सोर्सिंग',
    'whyUs.item4.desc': 'लहसुन स्थानीय क्षेत्रीय उत्पादकों से प्राप्त किया जाता है और किस्म और परिपक्वता उपयुक्तता के लिए चुना जाता है।',

    // ─── Nutrition ─────────────────────────────────────────────────
    'nutrition.badge': 'संरचना',
    'nutrition.title': 'पोषण प्रोफाइल',
    'nutrition.subtitle': 'प्रति 100g अनुमानित मान। वास्तविक संरचना किण्वन अवधि, तापमान और स्रोत किस्म के अनुसार भिन्न होती है।',
    'nutrition.note': 'कई प्रकाशित विश्लेषणों से संकलित डेटा। मान दिशात्मक हैं — सटीक आंकड़े बैच और अध्ययनों में काफी भिन्न होते हैं।',

    // ─── Black Garlic — Process ────────────────────────────────────
    'process.badge': 'किण्वन प्रक्रिया',
    'process.title': 'काला लहसुन कैसे बनाया जाता है',
    'process.subtitle': 'एक धीमी, एकल-सामग्री प्रक्रिया। तापमान और आर्द्रता पूरे समय नियंत्रित।',
    'bg.process.step1.title': 'बल्ब चयन',
    'bg.process.step1.desc': 'पूरे लहसुन के बल्बों को आकार एकरूपता, त्वचा अखंडता और चीनी सामग्री के लिए चुना जाता है।',
    'bg.process.step2.title': 'कक्ष तैयारी',
    'bg.process.step2.desc': 'बल्बों को ताप चक्र शुरू होने से पहले 80-90% सापेक्ष आर्द्रता के लिए कैलिब्रेट किए गए किण्वन कक्षों में रखा जाता है।',
    'bg.process.step3.title': 'किण्वन',
    'bg.process.step3.desc': '30-40 दिनों के लिए 60-80°C पर रखा जाता है। मेलार्ड प्रतिक्रिया और एंजाइमेटिक गतिविधि लौंग को बदलती है।',
    'bg.process.step4.title': 'निरीक्षण और पैकेजिंग',
    'bg.process.step4.desc': 'तैयार बल्बों का पैकेजिंग से पहले रंग एकरूपता और बनावट के लिए मूल्यांकन किया जाता है।',

    // ─── Comparison ────────────────────────────────────────────────
    'comparison.badge': 'काला बनाम ताजा',
    'comparison.title': 'वे कैसे भिन्न हैं',
    'comparison.subtitle': 'किण्वन के दौरान देखे गए दिशात्मक परिवर्तन।',
    'comparison.nutrient': 'घटक',
    'comparison.blackGarlic': 'काला लहसुन',
    'comparison.freshGarlic': 'ताजा लहसुन',
    'comparison.change': 'दिशा',
    'comparison.lower': 'कम',
    'comparison.sac': 'S-Allyl-Cysteine',
    'comparison.polyphenols': 'पॉलीफेनोल्स',
    'comparison.antioxidant': 'एंटीऑक्सीडेंट मार्कर',
    'comparison.calories': 'कैलोरी',
    'comparison.sugar': 'प्राकृतिक शर्करा',
    'comparison.allicin': 'एलिसिन',
    'comparison.note': 'केवल दिशात्मक संकेतक। सटीक मान बैच, स्रोत सामग्री और किण्वन स्थितियों में काफी भिन्न होते हैं।',

    // ─── Recipes ───────────────────────────────────────────────────
    'recipes.badge': 'रसोई में',
    'recipes.title': 'पाक अनुप्रयोग',
    'recipes.subtitle': 'काला लहसुन चटनी से लेकर ग्लेज़ तक के अनुप्रयोगों में काम करता है।',
    'recipes.ingredients': 'मुख्य सामग्री',
    'recipes.minutes': 'मिनट',
    'recipes.servings': 'सर्विंग',
    'recipes.easy': 'आसान',
    'recipes.medium': 'मध्यम',
    'recipes.hard': 'उन्नत',
    'recipe1.name': 'ब्लैक गार्लिक ऐओली',
    'recipe1.description': 'उमामी-फॉरवर्ड ऐओली। स्प्रेड, डिप या ग्रिल्ड मीट के लिए फिनिशिंग सॉस के रूप में काम करती है।',
    'recipe1.ingredients': 'काला लहसुन, अंडे की जर्दी, जैतून का तेल, नींबू का रस, डिजॉन सरसों',
    'recipe2.name': 'ब्लैक गार्लिक पास्ता',
    'recipe2.description': 'काले लहसुन, अच्छे जैतून के तेल और पुराने परमेसन से तैयार सरल पास्ता।',
    'recipe2.ingredients': 'स्पेगेटी, काला लहसुन, पैनसेटा, परमेसन, जैतून का तेल, ताजी जड़ी-बूटियां',
    'recipe3.name': 'ब्लैक गार्लिक बटर',
    'recipe3.description': 'काले लहसुन और थाइम के साथ कंपाउंड बटर। स्टेक को साफ तरीके से फिनिश करता है।',
    'recipe3.ingredients': 'अनसाल्टेड बटर, काला लहसुन, ताजा थाइम, समुद्री नमक',
    'recipe4.name': 'ब्लैक गार्लिक ग्लेज़्ड सैल्मन',
    'recipe4.description': 'काले लहसुन और शहद की ग्लेज़ के साथ पैन-सीयर्ड सैल्मन।',
    'recipe4.ingredients': 'सैल्मन फ़िलेट, काला लहसुन, शहद, सोया सॉस, अदरक, तिल का तेल',

    // ─── FAQ ───────────────────────────────────────────────────────
    'faq.badge': 'सामान्य प्रश्न',
    'faq.title': 'FAQ',
    'faq.subtitle': 'भंडारण, उपयोग, स्वाद और सोर्सिंग — सीधे उत्तर।',
    'faq.storage.question': 'काले लहसुन को कैसे संग्रहित करें?',
    'faq.storage.answer': 'बंद, सीधी रोशनी से दूर ठंडी सूखी जगह में रखें। खोलने के बाद, फ्रिज में रखें और 2-3 महीने में उपयोग करें। पूरे बल्ब 30 दिनों तक कमरे के तापमान पर रखे जा सकते हैं।',
    'faq.usage.question': 'काले लहसुन का खाना पकाने में उपयोग कैसे करें?',
    'faq.usage.answer': 'कच्चा या पका हुआ इस्तेमाल किया जा सकता है। सॉस, ड्रेसिंग और कंपाउंड बटर में मैश करें। पास्ता, पिज्जा या रिसोटो में डालें।',
    'faq.taste.question': 'काले लहसुन का स्वाद कैसा होता है?',
    'faq.taste.answer': 'मीठा, तीखा और स्वादिष्ट — बाल्सामिक, इमली और गुड़ के नोट्स के साथ। कच्चे लहसुन की तीखापन नहीं। बनावट मुलायम और फैलाने योग्य।',
    'faq.safety.question': 'क्या यह सभी के लिए सुरक्षित है?',
    'faq.safety.answer': 'आम तौर पर हां — कच्चे लहसुन की तुलना में पाचन पर हल्का। एंटीकोआगुलेंट दवाएं लेने वालों को चिकित्सक से परामर्श करना चाहिए।',
    'faq.purchasing.question': 'खरीदते समय क्या देखें?',
    'faq.purchasing.answer': 'बिना सफेद धब्बे या ढालू के समान रूप से काले, चमकदार लौंग। बनावट नरम लेकिन मुलायम नहीं। 30-40 दिन किण्वन सर्वोत्तम परिणाम देता है।',
    'faq.shelfLife.question': 'काला लहसुन कितने समय तक चलता है?',
    'faq.shelfLife.answer': 'व्यावसायिक रूप से पैक और बंद: 12-24 महीने। खोलने के बाद: फ्रिज में रखे 3 महीने तक।',

    // ─── B2B Section ───────────────────────────────────────────────
    'b2b.badge': 'पूछताछ',
    'b2b.title': 'थोक और व्यापार पूछताछ',
    'b2b.subtitle': 'उपभोक्ता और व्यापार दोनों अनुरोधों के लिए एक फॉर्म। सही विवरण के लिए पूछताछ का प्रकार चुनें।',
    'b2b.inquiryType': 'पूछताछ का प्रकार',
    'b2b.consumer': 'उपभोक्ता',
    'b2b.bulk': 'थोक / B2B',
    'b2b.contactName': 'संपर्क नाम',
    'b2b.contactName.placeholder': 'आपका नाम',
    'b2b.contactNumber': 'संपर्क नंबर',
    'b2b.contactNumber.placeholder': 'फोन / WhatsApp',
    'b2b.email': 'ईमेल',
    'b2b.email.placeholder': 'name@company.com',
    'b2b.location': 'स्थान',
    'b2b.location.placeholder': 'शहर, राज्य',
    'b2b.companyName': 'कंपनी का नाम',
    'b2b.companyName.placeholder': 'पंजीकृत व्यवसाय नाम',
    'b2b.businessType': 'व्यवसाय का प्रकार',
    'b2b.distributor': 'वितरक',
    'b2b.exporter': 'निर्यातक',
    'b2b.horeca': 'HoReCa',
    'b2b.retail': 'खुदरा',
    'b2b.other': 'अन्य',
    'b2b.products': 'रुचि के उत्पाद',
    'b2b.products.placeholder': 'काला लहसुन, छिला लहसुन, फ्रीज़ ड्राइड...',
    'b2b.quantity': 'अनुमानित मासिक मात्रा',
    'b2b.quantity.placeholder': 'जैसे 500 kg / माह',
    'b2b.message': 'संदेश',
    'b2b.message.bulk.placeholder': 'उत्पाद विनिर्देश, मात्रा अपेक्षाएं और डिलीवरी समयसीमा साझा करें।',
    'b2b.message.consumer.placeholder': 'बताएं हम आपकी कैसे मदद कर सकते हैं।',
    'b2b.submit': 'पूछताछ जमा करें',

    // ─── Peeled Garlic Page ────────────────────────────────────────
    'peeled.badge': 'लहसुन सामग्री',
    'peeled.title1': 'छिला',
    'peeled.title2': 'फ्रोज़न लहसुन',
    'peeled.description': 'साफ, सुसंगत रूप से प्रसंस्कृत छिले लहसुन के लौंग — होरेका रसोई, खाद्य प्रोसेसर और थोक रिपैकर के लिए तैयार।',
    'peeled.howMade.title': 'यह कैसे बनाया जाता है',
    'peeled.howMade.subtitle': 'साझा लहसुन प्रसंस्करण पाइपलाइन के बाद, छिले लहसुन को अंतिम ग्रेडिंग और पैकेजिंग चरणों से गुजरना होता है।',
    'peeled.specs.title': 'उत्पाद विनिर्देश',
    'peeled.step1.title': 'पोस्ट-पाइपलाइन प्रवेश',
    'peeled.step1.desc': 'लौंग साझा प्रसंस्करण लाइन से आते हैं — धुले, केन्द्रापसारक सूखे, रंग-छंटे और मैन्युअल रूप से निरीक्षण किए गए।',
    'peeled.step2.title': 'ग्रेड पृथक्करण',
    'peeled.step2.desc': 'लौंग को एकरूपता के लिए ग्राहक विनिर्देशों को पूरा करने के लिए आकार और दृश्य ग्रेड के आधार पर अलग किया जाता है।',
    'peeled.step3.title': 'ठंडा करना या परिवेश होल्ड',
    'peeled.step3.desc': 'डिस्पैच प्रोटोकॉल के अनुसार, लौंग को शून्य के करीब ठंडा किया जाता है या नियंत्रित परिवेश तापमान पर रखा जाता है।',
    'peeled.step4.title': 'पैकेजिंग',
    'peeled.step4.desc': 'खरीदार की आवश्यकता के अनुसार फूड-ग्रेड पाउच या बल्क कार्टन में पैक।',
    'peeled.spec1.label': 'भंडारण',
    'peeled.spec1.value': '0-4°C ठंडा या परिवेश',
    'peeled.spec2.label': 'शेल्फ लाइफ',
    'peeled.spec2.value': 'जमे हुए 12 महीने तक',
    'peeled.spec3.label': 'पैक प्रारूप',
    'peeled.spec3.value': 'बल्क कार्टन, रिटेल पाउच',
    'peeled.spec4.label': 'MOQ',
    'peeled.spec4.value': 'परक्राम्य — B2B पूछताछ',
    'peeled.spec5.label': 'गुणवत्ता',
    'peeled.spec5.value': 'रंग-छंटे + मैन्युअल निरीक्षण',
    'peeled.spec6.label': 'उपयुक्त',
    'peeled.spec6.value': 'होरेका, प्रोसेसर, रिपैकर',

    // ─── Freeze Dried Page ─────────────────────────────────────────
    'freeze.badge': 'निर्जलित उत्पाद',
    'freeze.title1': 'फ्रीज़',
    'freeze.title2': 'ड्राइड उत्पाद',
    'freeze.description': 'कम तापमान पर सब्लिमेशन ड्राइंग जो स्वाद, रंग और पोषण को संरक्षित करती है — लहसुन और केले में कई प्रारूपों में आपूर्ति।',
    'freeze.variants.title': 'उत्पाद प्रकार',
    'freeze.howMade.title': 'यह कैसे बनाया जाता है',
    'freeze.howMade.subtitle': 'फ्रीज़ ड्राइंग वह संरक्षित करती है जो पारंपरिक ड्राइंग नष्ट करती है — स्वाद वाष्पशील, कोशिका संरचना और पोषण घनत्व।',
    'freeze.specs.title': 'उत्पाद विनिर्देश',
    'freeze.product1.name': 'फ्रीज़ ड्राइड लहसुन',
    'freeze.product1.desc': 'दाने, पाउडर या फ्लेक रूप में केंद्रित लहसुन स्वाद। मसाला मिश्रण, इंस्टेंट खाद्य पदार्थ और खाद्य निर्माण के लिए आदर्श।',
    'freeze.product2.name': 'फ्रीज़ ड्राइड केला',
    'freeze.product2.desc': 'प्राकृतिक रूप से मीठे फ्रीज़ ड्राइड केले के स्लाइस और पाउडर। अनाज, स्नैक मिक्स और स्वास्थ्य खाद्य अनुप्रयोगों के लिए उपयुक्त।',
    'freeze.step1.title': 'पोस्ट-पाइपलाइन प्रवेश',
    'freeze.step1.desc': 'छिले, धुले और निरीक्षण किए गए लौंग साझा पाइपलाइन के बाद फ्रीज़-ड्राय लाइन में प्रवेश करते हैं।',
    'freeze.step2.title': 'प्री-फ्रीजिंग',
    'freeze.step2.desc': 'कोशिकीय संरचना को लॉक करने और अस्थिर स्वाद यौगिकों को संरक्षित करने के लिए लौंग या स्लाइस को तेज़ी से जमाया जाता है।',
    'freeze.step3.title': 'सब्लिमेशन ड्राइंग',
    'freeze.step3.desc': 'जमे हुए उत्पाद को वैक्यूम चेंबर में रखा जाता है जहां बर्फ सीधे वाष्प में बदल जाती है।',
    'freeze.step4.title': 'मिलिंग और साइज़िंग',
    'freeze.step4.desc': 'सूखे उत्पाद को खरीदार के विनिर्देश के अनुसार दाने, पाउडर या फ्लेक में मिलाया जाता है।',
    'freeze.step5.title': 'नमी जांच',
    'freeze.step5.desc': 'शेल्फ स्थिरता सुनिश्चित करने के लिए पैकेजिंग से पहले प्रति बैच अंतिम नमी सामग्री सत्यापित।',
    'freeze.step6.title': 'पैकेजिंग',
    'freeze.step6.desc': 'नमी-बाधा पाउच या बल्क कंटेनर में सील। कस्टम कट और प्राइवेट लेबल उपलब्ध।',
    'freeze.spec1.label': 'भंडारण',
    'freeze.spec1.value': 'ठंडा, सूखा — परिवेश स्थिर',
    'freeze.spec2.label': 'शेल्फ लाइफ',
    'freeze.spec2.value': 'सील 24 महीने तक',
    'freeze.spec3.label': 'प्रारूप',
    'freeze.spec3.value': 'दाने, पाउडर, फ्लेक्स, स्लाइस',
    'freeze.spec4.label': 'MOQ',
    'freeze.spec4.value': 'परक्राम्य — B2B पूछताछ',
    'freeze.spec5.label': 'गुणवत्ता',
    'freeze.spec5.value': 'बैच नमी सत्यापित',
    'freeze.spec6.label': 'उपयुक्त',
    'freeze.spec6.value': 'मसाला, ड्राय ब्लेंड, खुदरा',

    // ─── Vacuum Fried Page ─────────────────────────────────────────
    'vacuum.badge': 'स्नैक और सामग्री लाइन',
    'vacuum.title1': 'वैक्यूम',
    'vacuum.title2': 'फ्राइड उत्पाद',
    'vacuum.description': 'कम दबाव में फ्राइंग जो कुरकुरा बनावट, जीवंत रंग और कम तेल सामग्री प्रदान करती है — लहसुन, सब्जियों और फलियों में।',
    'vacuum.range.title': 'उत्पाद श्रृंखला',
    'vacuum.range.subtitle': 'लहसुन, सब्जियों, फलियों और फलों में सात वैक्यूम फ्राइड उत्पाद।',
    'vacuum.howMade.title': 'यह कैसे बनाया जाता है',
    'vacuum.howMade.subtitle': 'वैक्यूम फ्राइंग पारंपरिक फ्राइंग की तुलना में काफी कम तापमान पर काम करती है।',
    'vacuum.specs.title': 'उत्पाद विनिर्देश',
    'vacuum.product1.name': 'वैक्यूम फ्राइड लहसुन',
    'vacuum.product1.desc': 'केंद्रित स्वाद के साथ कुरकुरे लहसुन चिप्स। पारंपरिक तले लहसुन की तुलना में कम तेल सामग्री।',
    'vacuum.product2.name': 'वैक्यूम फ्राइड भिंडी',
    'vacuum.product2.desc': 'संरक्षित हरे रंग के साथ नाजुक कुरकुराहट। स्वास्थ्य-उन्मुख स्नैक अनुप्रयोगों में लोकप्रिय।',
    'vacuum.product3.name': 'वैक्यूम फ्राइड आलू',
    'vacuum.product3.desc': 'मानक फ्राइंग की तुलना में काफी कम तेल अवशोषण के साथ हल्के, कुरकुरे आलू के स्लाइस।',
    'vacuum.product4.name': 'वैक्यूम फ्राइड चना',
    'vacuum.product4.desc': 'उच्च-प्रोटीन स्नैक बेस। मसालेदार और सादे प्रारूपों के लिए उपयुक्त कुरकुरा बनावट।',
    'vacuum.product5.name': 'वैक्यूम फ्राइड राजमा',
    'vacuum.product5.desc': 'मज़बूत, कुरकुरा बनावट। ट्रेल मिक्स, स्नैक ब्लेंड और रिटेल पैक के लिए उपयुक्त।',
    'vacuum.product6.name': 'वैक्यूम फ्राइड शकरकंद',
    'vacuum.product6.desc': 'कम तापमान फ्राइंग से जीवंत रंग प्रतिधारण के साथ प्राकृतिक रूप से मीठा स्वाद प्रोफाइल।',
    'vacuum.product7.name': 'वैक्यूम फ्राइड केला',
    'vacuum.product7.desc': 'प्राकृतिक मिठास के साथ कुरकुरे केले चिप्स। सादा या हल्के मसाले में उपलब्ध।',
    'vacuum.step1.title': 'कच्चे माल की तैयारी',
    'vacuum.step1.desc': 'सब्जियों और फलियों को साफ किया जाता है, जहां आवश्यक हो छीला जाता है, और समान फ्राइंग के लिए लक्ष्य आयामों में काटा जाता है।',
    'vacuum.step2.title': 'ब्लैंचिंग',
    'vacuum.step2.desc': 'संक्षिप्त ताप उपचार फ्राइंग के दौरान भूरेपन और ऑफ-फ्लेवर का कारण बनने वाले एंजाइमों को निष्क्रिय करता है।',
    'vacuum.step3.title': 'वैक्यूम फ्राइंग',
    'vacuum.step3.desc': 'उत्पाद को कम दबाव में तला जाता है — पानी और तेल के क्वथनांक को काफी कम करता है।',
    'vacuum.step4.title': 'केन्द्रापसारक डी-ऑयलिंग',
    'vacuum.step4.desc': 'अतिरिक्त सतह तेल को फ्राय के तुरंत बाद केन्द्रापसारक घुमाव द्वारा हटाया जाता है।',
    'vacuum.step5.title': 'सीज़निंग (वैकल्पिक)',
    'vacuum.step5.desc': 'सादा या मसालेदार वेरिएंट उपलब्ध। मसाला मिश्रण नियंत्रित टम्बलिंग के तहत लगाया जाता है।',
    'vacuum.step6.title': 'पैकेजिंग',
    'vacuum.step6.desc': 'नाइट्रोजन-फ्लश पैकेजिंग विस्तारित शेल्फ लाइफ के लिए। बल्क, रिटेल और प्राइवेट-लेबल प्रारूप उपलब्ध।',
    'vacuum.spec1.label': 'प्रक्रिया तापमान',
    'vacuum.spec1.value': '120°C से नीचे वैक्यूम फ्राइंग',
    'vacuum.spec2.label': 'शेल्फ लाइफ',
    'vacuum.spec2.value': 'सील 12 महीने तक',
    'vacuum.spec3.label': 'प्रारूप',
    'vacuum.spec3.value': 'सादा, मसालेदार, प्राइवेट लेबल',
    'vacuum.spec4.label': 'MOQ',
    'vacuum.spec4.value': 'परक्राम्य — B2B पूछताछ',
    'vacuum.spec5.label': 'गुणवत्ता',
    'vacuum.spec5.value': 'बैच तेल और नमी जांच',
    'vacuum.spec6.label': 'उपयुक्त',
    'vacuum.spec6.value': 'स्नैक रिटेल, होरेका, निर्यात',

    // ─── Roasted Masala Page ───────────────────────────────────────
    'roasted.badge': 'फ्लेवर्ड स्नैक लाइन',
    'roasted.title1': 'रोस्टेड',
    'roasted.title2': 'मसाला लहसुन',
    'roasted.description': 'नियंत्रित मसाला कोटिंग के साथ पूरे रोस्टेड लहसुन के लौंग — रिटेल स्नैकिंग, गिफ्टिंग और फूडसर्विस के लिए विकसित।',
    'roasted.highlights.title': 'उत्पाद मुख्य विशेषताएं',
    'roasted.howMade.title': 'यह कैसे बनाया जाता है',
    'roasted.howMade.subtitle': 'रोस्टिंग और मसाला कोटिंग नियंत्रित बैच में की जाती है।',
    'roasted.specs.title': 'उत्पाद विनिर्देश',
    'roasted.highlight1.title': 'कस्टम मसाला प्रोफाइल',
    'roasted.highlight1.desc': 'मसाला तीव्रता और मिश्रण संरचना चैनल के अनुसार समायोजित — रिटेल के लिए हल्की, फूडसर्विस के लिए तीखी।',
    'roasted.highlight2.title': 'प्राइवेट लेबल तैयार',
    'roasted.highlight2.desc': 'रिपैकर और प्राइवेट लेबल खरीदारों के लिए बिना ब्रांड के आपूर्ति। अनुरोध पर कस्टम पैक आकार।',
    'roasted.highlight3.title': 'स्नैक और सामग्री उपयोग',
    'roasted.highlight3.desc': 'रेडी-टू-ईट स्नैक या खाद्य निर्माण के लिए फ्लेवर्ड लहसुन सामग्री के रूप में उपयुक्त।',
    'roasted.step1.title': 'पोस्ट-पाइपलाइन प्रवेश',
    'roasted.step1.desc': 'छिले, धुले और निरीक्षण किए गए लौंग साझा पाइपलाइन के बाद रोस्टिंग लाइन में प्रवेश करते हैं।',
    'roasted.step2.title': 'रोस्टिंग',
    'roasted.step2.desc': 'नियंत्रित बैच में लौंग को जलने या असमान भूरेपन के बिना कैरामेलाइज़्ड स्वाद प्रोफाइल विकसित करने के लिए रोस्ट किया जाता है।',
    'roasted.step3.title': 'ठंडा करना',
    'roasted.step3.desc': 'रोस्टेड लौंग को कोटिंग से पहले कैरीओवर कुकिंग रोकने और बनावट स्थिर करने के लिए जल्दी ठंडा किया जाता है।',
    'roasted.step4.title': 'मसाला मिश्रण',
    'roasted.step4.desc': 'मसाला मिश्रण घर में तैयार किए जाते हैं। तीव्रता और संरचना खरीदार विनिर्देश के अनुसार समायोज्य।',
    'roasted.step5.title': 'कोटिंग',
    'roasted.step5.desc': 'नियंत्रित टम्बलिंग के तहत मसाला लगाया जाता है ताकि सभी लौंग पर समान, सुसंगत कोटिंग सुनिश्चित हो।',
    'roasted.step6.title': 'पैकेजिंग',
    'roasted.step6.desc': 'स्नैक पाउच, जार या फूडसर्विस बल्क प्रारूप में पैक। प्राइवेट लेबल और कस्टम मसाला प्रोफाइल उपलब्ध।',
    'roasted.spec1.label': 'भंडारण',
    'roasted.spec1.value': 'ठंडा, सूखा — परिवेश स्थिर',
    'roasted.spec2.label': 'शेल्फ लाइफ',
    'roasted.spec2.value': 'सील 9 महीने तक',
    'roasted.spec3.label': 'प्रारूप',
    'roasted.spec3.value': 'स्नैक पाउच, जार, बल्क',
    'roasted.spec4.label': 'MOQ',
    'roasted.spec4.value': 'परक्राम्य — B2B पूछताछ',
    'roasted.spec5.label': 'गुणवत्ता',
    'roasted.spec5.value': 'बैच रोस्ट + कोटिंग जांच',
'products.peeled.name': 'छिली हुई जमी हुई लहसुन',
'products.peeled.method': 'यांत्रिक छीलना, धुलाई, सेंट्रीफ्यूगल सुखाना',
'products.peeled.formats': 'ठंडा थोक, सामान्य तापमान रिटेल पैक',
'products.freeze.name': 'फ्रीज़ ड्राइड उत्पाद',
'products.freeze.method': 'कम तापमान पर सब्लिमेशन सुखाना',
'products.freeze.formats': 'ग्रैन्यूल, पाउडर, फ्लेक्स, स्लाइस',
'products.vacuum.name': 'वैक्यूम फ्राइड उत्पाद',
'products.vacuum.method': '120°C से कम तापमान पर कम दबाव में तलना',
'products.vacuum.formats': 'सादा, मसालेदार, प्राइवेट लेबल',
'products.roasted.name': 'रोस्टेड मसाला लहसुन',
'products.roasted.method': 'मसाला कोटिंग के साथ नियंत्रित रोस्टिंग',
'products.roasted.formats': 'स्नैक पाउच, जार, थोक फूडसर्विस',
'products.blackGarlic.name': 'ब्लैक गार्लिक',
'products.blackGarlic.method': '30-40 दिन नियंत्रित किण्वन',
'products.blackGarlic.formats': 'पूरे बल्ब, छिली कलियाँ, थोक',

'contact.badge': 'संपर्क करें',
'contact.title1': 'संपर्क और',
'contact.title2': 'स्थान',
'contact.subtitle': 'थोक पूछताछ, व्यापार साझेदारी या उत्पाद जानकारी के लिए — सीधे हमसे संपर्क करें।',
'contact.address.title': 'पता',
'contact.phone.title': 'मोबाइल',
'contact.email.title': 'ईमेल',
    'roasted.spec6.label': 'उपयुक्त',
    'roasted.spec6.value': 'रिटेल स्नैक, गिफ्टिंग, होरेका',

    // ─── Footer ────────────────────────────────────────────────────
    'footer.tagline': 'शुभम फूड्स का एक उत्पाद',
    'footer.desc': 'सुसंगत गुणवत्ता, प्रामाणिक स्वाद और सावधानीपूर्वक प्रसंस्कृत खाद्य उत्पाद प्रदान करने के लिए प्रतिबद्ध।',
    'footer.address': 'जादेश्वर ग्राम पंचायत के पास, जादेश्वर, जि. भरूच (गुजरात)',
    'footer.disclaimer': 'शोध उद्धरण सूचनात्मक उद्देश्यों के लिए प्रदान किए जाते हैं। यह चिकित्सा सलाह नहीं है।',
    'footer.rights': '© 2026 Shubham Foods. All rights reserved.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');
  useEffect(() => { setLanguage('en'); }, []);

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

